### ISSUE TITLE
"Starting Metals Server" forvever.

### ISSUE THREAD

**Issue by krizald** [scalameta/metals-vscode#1028]
### Environment: 
OS: Windows 10
VS Code: 1.68.1
Metals extension: 1.17.7
Metals: 0.11.6
Java:1.8.0_331
Scala: 2.12.15
sbt:1.6.2
$env:JAVA_HOME C:\Program Files\Java\jdk1.8.0_331

It's a very simple "hello world" project. Code seems compiled. but VS code still showing "Staring metals server" with spinning icon. I also tried to clicked the "run" on top of the Main class, but nothing happens,

### Screenshot
![2022-06-17_8-59-22](https://user-images.githubusercontent.com/7716750/174313238-0f664c86-f01d-46e5-87fb-8825abc90d78.png)

### Extension log:
Java home: C:\Program Files\Java\jdk1.8.0_331
Metals version: 0.11.6
2022.06.17 08:33:41 INFO  logging to file D:\repo\scala-hello-world\.metals\metals.log
2022.06.17 08:33:41 INFO  Started: Metals version 0.11.6 in workspace 'D:\repo\scala-hello-world' for client Visual Studio Code 1.68.1.
2022.06.17 08:33:42 INFO  time: initialize in 0.78s
Initializing Scala Debugger
2022.06.17 08:33:42 INFO  Flyway Community Edition 8.5.10 by Redgate
2022.06.17 08:33:42 INFO  See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.10
2022.06.17 08:33:42 INFO  
2022.06.17 08:33:46 INFO  Database: jdbc:h2:file:D:\repo\scala-hello-world\.metals\metals (H2 2.1)
2022.06.17 08:33:46 WARN  Flyway upgrade recommended: H2 2.1.212 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.1.210.
2022.06.17 08:33:46 INFO  Successfully validated 3 migrations (execution time 00:00.017s)
2022.06.17 08:33:46 INFO  Current version of schema "PUBLIC": 3
2022.06.17 08:33:46 INFO  Schema "PUBLIC" is up to date. No migration necessary.
2022.06.17 08:33:47 INFO  Attempting to connect to the build server...
2022.06.17 08:33:47 INFO  skipping build import with status 'Installed'
2022.06.17 08:33:49 INFO  no build target found for D:\repo\scala-hello-world\src\main\scala\Main.scala. Using presentation compiler with project's scala-library version: 3.1.2
2022.06.17 08:33:51 INFO  time: code lens generation in 3.95s
2022.06.17 08:33:51 INFO  time: code lens generation in 3.95s
2022.06.17 08:33:52 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at D:\repo\scala-hello-world\.metals\bsp.trace.json or d:\repo\scala-hello-world\null\scalameta\metals\cache\bsp.trace.json
2022.06.17 08:33:52 INFO  Attempting to connect to the build server...
2022.06.17 08:33:52 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at D:\repo\scala-hello-world\project\.metals\bsp.trace.json or d:\repo\scala-hello-world\null\scalameta\metals\cache\bsp.trace.json
2022.06.17 08:33:52 INFO  time: Connected to build server in 6.21s
2022.06.17 08:33:52 INFO  Connected to Build server: Bloop v1.5.0-18-003e6c7b
2022.06.17 08:33:53 INFO  time: Imported build in 0.18s
2022.06.17 08:33:55 INFO  time: indexed workspace in 1.6s

**Comment by krizald** [comment]
PS. I downgraded extension to 1.13.6 with all same settings. And it works

**Comment by krizald** [comment]
> Thanks for reporting! Looks like the issue is with the status bar and it's never refreshed. The server has actually started. Does it happen to you on 1.17.0 version?

Hi tgodzik, 

I changed to 1.17.0 and it works like a charm. 

This issue with 1.17.7 seems not a display bug. the "Debug" doesn't work at all, when showing "Start Metals Server".

**Comment by tgodzik** [comment]
`1.17.7` might have been broken, since they're prerelease versions (not stable). The newest one should work correctly.

**Comment by dzx-dzx** [comment]
I'm afraid this bug has gone into the latest formal release `1.18.0`... The symptom is the same.

**Comment by tgodzik** [comment]
@dzx-dzx I haven't seen any issue like that in the newest release and no one else reported it, so this might be something else.

What do you get in the logs? Could you report it as a new issue with the output of `.metals/metals.log` or just `Output(Metals)` if the server hasn't started?

**Comment by dzx-dzx** [comment]
> @dzx-dzx I haven't seen any issue like that in the newest release and no one else reported it, so this might be something else.
> 
> What do you get in the logs? Could you report it as a new issue with the output of `.metals/metals.log` or just `Output(Metals)` if the server hasn't started?

The log is practically the same, ending with `INFO time: indexed workspace in ***s`. I will create a separate issue soon.
