### ISSUE TITLE
Automatic build import is not supported for sbt <unknown>

### ISSUE THREAD

**Issue by xiligey** [scalameta/metals-vscode#108]
When I run the command "Metals: Import build", error comes:
Automatic build import is not supported for sbt <unknown>. To fix this problem, upgrade to sbt v0.13.17+

My settings of Metals is null (I didn't change any default setting of metals )

**Comment by olafurpg** [comment]
Thanks for reporting! What happens when you add a `project/build.properties` file?

```scala
// project/build.properties
sbt.version=1.2.8
```

**Comment by tgodzik** [comment]
@olafurpg 's suggestion should help, let us know if you have any further issues.
