### ISSUE TITLE
SBT loses colors when running from Metals

### ISSUE THREAD

**Issue by grpvw** [scalameta/metals-vscode#1090]
Metals 1.18

Build server is set to SBT.
Connect with the `sbt -client` command to the running server,
the CLI doesn't print with colors.
Tried to add `sbt --colors=always`, didn't help.
When running the same project with standard sbt runner, colors are shown.

Expected:
Show colors in sbt cli.

**Comment by tgodzik** [comment]
Thanks for reporting! This needs to be fixed in https://github.com/scalameta/metals-feature-requests/issues/243

Alternatively, you can work around it for now with `-Dsbt.color=always`

**Comment by grpvw** [comment]
Unfortunately, didn't work.

Another solution suggested on Discord works as expected.
> Andreas — Today at 20:36
> you can add -Dsbt.log.noformat=false to your .jvmopts file in the root of your project and get back the colored output even when Metals starts SBT

Then don't forget to exit Vscode and kill sbt from terminal, so it catches the change.
