### ISSUE TITLE
Wrong highlighting with `derives` in Scala 3

### ISSUE THREAD

**Issue by Meowcolm024** [scalameta/metals-vscode#1091]
**Describe the bug**

(Possibly a bug?)
I don't know if it is a VSCode only issue (but I suppose it is related to `Semantic Highlight`)

Scala Version: 3.1.3

**To Reproduce** Steps to reproduce the behavior:

<img width="514" alt="螢幕截圖 2022-08-03 下午3 43 24" src="https://user-images.githubusercontent.com/23007687/182552491-6ac0a6bb-59d0-45a3-aeb4-b0de5f728984.png">

**Notice how `D` has a different color to `C` in line 14**
(Both in `Ayu Dark` and `Community Material`)

**Expected behavior**

`D` should probably have the same color as `C`

**Installation:**

- Operating system: macOS
- VSCode version: 1.69.2 (Universal)
- VSCode extension version: v1.18.0
- Metals version: 0.11.7

**Comment by tgodzik** [comment]
Thanks for reporting! Would you mind opening an issue in https://github.com/scala/vscode-scala-syntax ? It's something we need on the Scala syntax side, which is actually used in a number of other places.

**Comment by Meowcolm024** [comment]
> Thanks for reporting! Would you mind opening an issue in https://github.com/scala/vscode-scala-syntax ? It's something we need on the Scala syntax side, which is actually used in a number of other places.

I see, Thx :P

**Comment by Meowcolm024** [comment]
> Thanks for reporting! Would you mind opening an issue in https://github.com/scala/vscode-scala-syntax ? It's something we need on the Scala syntax side, which is actually used in a number of other places.

So we can close the issue here now and leave it to `https://github.com/scala/vscode-scala-syntax`?

**Comment by tanishiking** [comment]
Yep, let close this issue for https://github.com/scala/vscode-scala-syntax/issues/239
Thank you for reporting! @Meowcolm024
