### ISSUE TITLE
Cannot correctly lint when open file from vscode workspace

### ISSUE THREAD

**Issue by xcmz** [scalameta/metals-vscode#1109]
When directly open file from vscode explorer, metals cannot lint anything.

**To Reproduce** Steps to reproduce the behavior:

Vscode Version: 1.70.1 (Universal)
Metals Version: 0.11.8

1. In a new workspace, create any scala file, write any syntax-error code.
2. open that file from vscode explorer
3. check the problem panel, find that problematic file, click it
4. Here we can see there are two opened file, the one opened from vscode explorer linted nothing. The other one opened from problem panel are correctly linted

If turn on breadcrumbs.filePath in vscode, we can see the two opened files have different path. The one opened from explorer shows a path relative to workspace, Another shows an absolute path. It seems metals are confused by relative and absolute path .

**Screenshots**
file opened from vscode explorer
<img width="835" alt="截屏2022-08-16 13 31 02" src="https://user-images.githubusercontent.com/48869373/184804749-3ee97f73-09e9-4631-b6a9-435bc980fbe9.png">

file opened from problem panel.
<img width="857" alt="截屏2022-08-16 13 31 45" src="https://user-images.githubusercontent.com/48869373/184804857-358b66b1-0a59-4dd2-8f27-90afbd3c6ff1.png">

**Installation:**

- Operating system: Linux
- VSCode version: 1.70.1 (Universal)
- Metals version: 0.11.8

**Search terms**
lint

**Comment by tgodzik** [comment]
Thanks for reporting! This seems to be an issue with VS Code, though I can't reproduce it on my side. Are there any symlinks used in that workspace?  Metals should use the paths provided by the editor in this case, so there should not be any change to the error information.

**Comment by xcmz** [comment]
> Thanks for reporting! This seems to be an issue with VS Code, though I can't reproduce it on my side. Are there any symlinks used in that workspace? Metals should use the paths provided by the editor in this case, so there should not be any change to the error information.

Thanks! Its the symlinks problem. My workspace are opened via a symlink, instead of absolute path. Reopening it with absolute path solves my problem!
