### ISSUE TITLE
Metals server doesn't start

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals-vscode#1116]
**Describe the bug**

I see this in the output panel:

```
Java home: /nix/store/hpggzh7afi4qs2nm92gsn4drharb858d-zulu11.48.21-ca-jdk-11.0.11
Metals version: 0.11.8+25-04b682be-SNAPSHOT
Aug 18, 2022 4:50:16 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
```

and nothing else. I don't see Bloop running, but `scala.meta.metals.Main` is there in the `jps -l` output.

1. Update extension to 1.19.5
2. Open a Scala project
3. Open output panel (Metals)
4. See logs above

**Expected behavior**

The server works normally

**Screenshots**

After update:

<img width="1872" alt="image" src="https://user-images.githubusercontent.com/894884/185425961-eb27ed99-df65-4381-9ef0-56c5d533bae6.png">

Before update, on 1.18.8:

<img width="2620" alt="image" src="https://user-images.githubusercontent.com/894884/185426093-fec1628b-0911-4c20-aca4-38c56669da29.png">

**Installation:**

- Operating system: macOS
- VSCode version:  1.70.2
- VSCode extension version: 1.19.5
- Metals version: 0.11.8+25-04b682be-SNAPSHOT

**Additional context**

**Search terms**

Server start stuck

**Comment by dos65** [comment]
@kubukoz  Thanks for reporting!

Could you check if there is any additional info in `.metals/metals.log`?

**Comment by kubukoz** [comment]
There's this:

```
2022.08.18 17:26:34 INFO  tracing is enabled: /Users/kubukoz/Library/Caches/org.scalameta.metals/lsp.trace.json[0m
2022.08.18 17:26:34 WARN  Invalid value for property 'metals.verbose', required 'true|on' or 'false|off', but got ''. Using the default value 'false'[0m
2022.08.18 17:26:34 WARN  Invalid value for property 'metals.verbose', required 'true|on' or 'false|off', but got ''. Using the default value 'false'[0m
2022.08.18 17:26:34 INFO  logging to file /Users/kubukoz/projects/smithy-playground/.metals/metals.log[0m
2022.08.18 17:26:34 INFO  Started: Metals version 0.11.8+25-04b682be-SNAPSHOT in workspace '/Users/kubukoz/projects/smithy-playground' for client Visual Studio Code 1.70.2.[0m
2022.08.18 17:26:35 INFO  time: initialize in 0.69s[0m
```

but the server is still shown as starting, and no features work:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/894884/185433814-62739701-df57-46e0-8f03-b66495610b3b.png">

**Comment by kubukoz** [comment]
okay, I had that `-Dmetals.verbose` in my global `metals.serverProperties`, I set it to `-Dmetals.verbose=true and it's working again :D 

thanks for the pointer!
