### ISSUE TITLE
Consolidate client commands registration and validation

### ISSUE THREAD

**Issue by gabro** [scalameta/metals-vscode#123]
We currently register client commands in several locations.

Ideally, we should:

- define commands and their params in a single centralized point
- register them in bulk
- validate their arguments at runtime and use a typesafe model from then on (`io-ts` can help here)

**Comment by olafurpg** [comment]
Fixed in #155 ?

**Comment by gabro** [comment]
Sort of, the command registration is still a bit scattered and the validation leaves a lot to be desired. This is not a priority though. I'll close it to clear the issue queue
