### ISSUE TITLE
Running Metals in VS Code Snap build under Ubuntu fails

### ISSUE THREAD

**Issue by rvangsgaard** [scalameta/metals-vscode#127]
**Describe the bug**

Unable to download Metals. Error message
```Failed to download Metals, make sure you have an internet connection and the Java Home ...```

Maybe is related to https://github.com/scalameta/metals-vscode/issues/67, as a Snap build of VS Code seem similar to flatpak.

It works fine when installing the .deb package (64 bit) described here https://code.visualstudio.com/docs/setup/linux

**To Reproduce** Steps to reproduce the behavior:

1. Install VS Code from Ubuntu Snap store.
2. Start VS Code and open metals enabled project.
3. See error

**Installation:**

- Operating system: Ubuntu 19.04
- VSCode version: 1.36.1
- VSCode extension version: 1.5.1
- Metals version: 0.7.0

![image](https://user-images.githubusercontent.com/144689/61213627-1a4d9080-a6f5-11e9-99e3-79e131cceeb5.png)

**Search terms**

Failed to download Metals, make sure you have an internet connection and the Java Home '/usr/lib/jvm/java-8-openjdk-amd64/bin/java' is valid. You can configure the Java Home in the settings.See https://scalameta.org/metals/docs/editors/vscode.html#http-proxy for instructions if you are using an HTTP proxy.

Error while downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.12/1.1.0-M13-2/coursier-cli_2.12-1.1.0-M13-2-standalone.jar: /home/rva/.coursier/cache/v1/.structure.lock (No such file or directory), ignoring it

**Comment by tgodzik** [comment]
Thanks for reporting!

This looks weird, coursier on my machine is in `.cache/coursier` while in the report you specify
`.coursier/cache` I wonder what's the reason for this.

Where is your coursier cache located now with the deb package of VS Code?

**Comment by tgodzik** [comment]
Addressed it in https://github.com/scalameta/metals-vscode/pull/128

**Comment by rvamiracle** [comment]
Hi again, it seem the problem with my setup was permission based. The `.coursier` directory was owned by root. After deleting the directory, downloading of Metals finished successfully.

I cannot remember how the directory came to existence (it was almost one year old), and why the Metals downloader or Couriser tried to use it.

**Comment by tgodzik** [comment]
Ok, did Metals work properly with `snap`? I can remove the warning then.

**Comment by rvamiracle** [comment]
Yes, my findings are that Metals work properly with `snap`. Sorry about submitting the bug originally.

**Comment by rvangsgaard** [comment]
The original bug submitter here - yes, Metals work properly with `snap`.
