### ISSUE TITLE
Wrong execution time reports of test classes

### ISSUE THREAD

**Issue by d-albrecht** [scalameta/metals-vscode#1296]
**Describe the bug**

I have a pure Scala project with ScalaTest (AnyWordSpec-style) tests managed by sbt opened in VSCodium using metals. If I run individual tests, then I can see the correctly reported execution times in the VSCode "Testing" sidebar. But if I run a whole test class with several tests in it, the reporting is corrupted. VSCode annotates each individual test method with the execution time of the whole class, and hence (probably) calculates the whole class to take a multiple of the time (if you have ten individual tests, the whole class is said to take ten times the actual execution time).

I'm not completely sure, if metals is the problem here, but by deduction I think I can eliminate the Scala Lang (it's just the language), VSCode (it can run tests in all sorts of languages and some developer might have reported wrong test run times by now if there was a general bug) and sbt (I assume that no dedicated sbt processes are spawned but metals "emulates" sbt if used in VSCode) from the list of candidates. So, either the reported times by ScalaTest are bad (which they shouldn't be as the debug console shows reasonable output times) or metals misinterprets the output of ScalaTest. OR, the LSP design is insufficient and metals can't report more precise execution times to VSCode.

But either way, someone should probably look into that and at least pin-point the problematic component.

**To Reproduce** Steps to reproduce the behavior:

1. Create a test class (AnyWordSpec) in VSCode.
2. Create several test methods in this class that each take at least a few seconds to finish.
3. Either launch a single test method or the whole test class.
4. See execution times as reported in the Debug Console and and VSCode "Testing" sidebar

**Expected behavior**

The execution time of the class matches the reported time of ScalaTest from the console (and the time it takes in reality).
Each test method is annotated by a reasonable test execution time, even if you launch the whole class at once.

**Screenshots**

Report when launched individually:
![tests_individual](https://user-images.githubusercontent.com/5196458/211549170-0c24daa3-e580-4c41-83d1-23095a4ae0d6.png)

Report when launched together:
![tests_together](https://user-images.githubusercontent.com/5196458/211549197-d1c484f0-8539-4899-a704-e06aab6520cd.png)

**Installation:**

- Operating system: Linux (Fedora)
- VSCode version: 1.74.2
- VSCode extension version: 1.21.0
- Metals version: (found in VSCode settings, under `metals.serverVersion`) 0.11.10

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting!

@kpodsiad any idea where the issue might be at? Do we do it on the VS Code side or on the BSP side?

**Comment by kpodsiad** [comment]
Hey @d-albrecht, thanks for raising issue! Probably it is metals-vscode extension issue, I'll have a look ;)

**Comment by d-albrecht** [comment]
Quick additional note on that: I created the shown test class, later on moved it to another (sub-)project, but this move didn't go that well, in the way that the test class was still in the list of tests, but under the new project name, it didn't list the individual test methods anymore and when I launched the whole class again, it summed up to 15 seconds but couldn't open the test file again. I already know that I have to re-open VSCode from time to time to "fix" some issues with it, but I just wanted to add, that sometimes launching the whole class (under really strange circumstances) can result in the right times. Re-opening VSCode changed the times back to the wrong (accumulated) ones.

I'm open to further test specific things (if you can't reproduce this). Just tell me.

**Comment by tgodzik** [comment]
> I already know that I have to re-open VSCode from time to time to "fix" some issues with it, but I just wanted to add, that sometimes launching the whole class (under really strange circumstances) can result in the right times. Re-opening VSCode changed the times back to the wrong (accumulated) ones.

This looks like a separate reproducible error, could you raise an issue in `scalameta/metals`, this is probably an issue with server.

**Comment by kpodsiad** [comment]
ok, I managed to find an issue in some common debugging part. @tgodzik will you take a look?

**Comment by tgodzik** [comment]
Thanks @kpodsiad ! This should be available as soon as we bump scala dap in Bloop and sbt.

**Comment by d-albrecht** [comment]
> > I already know that I have to re-open VSCode from time to time to "fix" some issues with it, but I just wanted to add, that sometimes launching the whole class (under really strange circumstances) can result in the right times. Re-opening VSCode changed the times back to the wrong (accumulated) ones.
> 
> This looks like a separate reproducible error, could you raise an issue in `scalameta/metals`, this is probably an issue with server.

I would have to look into this more, but if this IS reproducible, I actually should. Most of the other "strange behaviors" I observed so far is more in the category of "after VSCode was open for a while and I took several (random) actions, at one point metals (or some other component in my tool-chain) starts to go off the rails and acts up". If you feel like the project would benefit from knowing about these rather random hiccups I could get them reported here (or in other appropriate places). But usually non-reproducible bugs are more often then not rather not that appreciated in bug trackers as they are harder to pin-point and actually fix. And about half the hiccups only happened once so far.

Btw (or: more on topic), thanks for the fix! Until this new version is out, I now know that I just can't rely on the reported test execution times, but that doesn't influence the correctness of the tests, so I'm not dependent on the new version to be available soon.

**Comment by tgodzik** [comment]
> If you feel like the project would benefit from knowing about these rather random hiccups I could get them reported here (or in other appropriate places). But usually non-reproducible bugs are more often then not rather not that appreciated in bug trackers as they are harder to pin-point and actually fix. And about half the hiccups only happened once so far.

It's fine to report them, we might close them after a while if indeed we can't reproduce them, but it lets us know the scope of some stability issues, which I aim to fix as much as possible.
