### ISSUE TITLE
No build targets were detected in this workspace so most functionality won't work

### ISSUE THREAD

**Issue by robsonpeixoto** [scalameta/metals-vscode#1316]
**Describe the bug**

The `run/debug` lenses is not showing because of the error "No build targets were detected in this workspace so most functionality won't work"

I tried to clean(`git clean -d -x -f`) the environment and re-import the project, but I it didn't work.

**To Reproduce** Steps to reproduce the behavior:

1. Go to https://github.com/robsonpeixoto/learn-scala-3
2. Open the project
3. Run `Metals: Run doctor`

**Expected behavior**

The lenses `run/debug` working.

**Screenshots**

![image](https://user-images.githubusercontent.com/124390/214595673-9e432788-8ebf-40d2-b416-dda17ee494cc.png)

![image](https://user-images.githubusercontent.com/124390/214596066-18da4d96-adaa-47e2-a841-5674a996c646.png)

**Installation:**

- Operating system: macOS
- VSCode version: 1.74.3
- VSCode extension version: v1.21.0
- Metals version: 0.11.10

**Search terms**

- `Ignoring decorations for non-active document`
- `no build target for`

**Comment by tgodzik** [comment]
Thanks for reporting! Did you manage to import the project? For sbt projects you need to first run an import. This should be suggested to you in a pop up, if not you can run in manually from the Metals tab.

**Comment by robsonpeixoto** [comment]
@tgodzik for some reason is not showing the `pop up`, but after run `>metals: Import build` the code lenses started to work again.

https://user-images.githubusercontent.com/124390/214698776-e1a876a2-1a0a-4159-a1d1-eb4a68d493b3.mp4
 

Thanks!
