### ISSUE TITLE
Scalameta fails to import project using Java 11

### ISSUE THREAD

**Issue by wfaler** [scalameta/metals-vscode#132]
From the latest release notes, I'm assuming that OpenJDK Java 11 is now supported, at least partially.
However, I still have isses using Java 11:
* I have set the JAVA_HOME for metals and can see it is being used by the output.
* I have a plain SBT project.

Output tab shows:
```
Java home: /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home
logging to file /Users/wfaler/dev/chaordic/cddhub/server/.metals/metals.log
time: initialize in 0.78s
skipping build import with status 'Failed'
```
Log file shows:
```
INFO  shutting down Metals
INFO  time: initialize in 0.78s
INFO  skipping build import with status 'Failed'
```

I initially suspected the issue was due to using a JDK module in `.sbtopts` like so:
```
-J-XX:MaxMetaspaceSize=512M
-J-Xmx2G
-J--add-modules=jdk.crypto.ec
```

But removing the sbt opts all together did not change the outcome when restarting.
Any ideas on how to further debug this? The log file sheds very little light.

**Comment by tgodzik** [comment]
Hi, thanks for reporting! Could you try running the import manually? If it fails before we don't rerun it, so this might have been a previous issue.

To run manually run `Import build` either from command palette or from Metals tab. Let me know if it fail again and what the log shows.

**Comment by wfaler** [comment]
Ah, that worked. Thank you, and sorry for polluting the issues, doh!

**Comment by tgodzik** [comment]
No worries, let us know if anything is wrong. Might ask also first on gitter and get a faster response, but if you see any issues don't hesitate to report them.
