### ISSUE TITLE
No symbol completion or go-to-definition in build.sbt

### ISSUE THREAD

**Issue by argv-minus-one** [scalameta/metals-vscode#136]
**Describe the bug**

Nothing happens when I Ctrl+click on a symbol in `build.sbt`. Ctrl+Space completion yields only textual completions, not smart ones. These functions work correctly in source files, just not in `build.sbt`. There is still syntax highlighting in `build.sbt`.

**To Reproduce** Steps to reproduce the behavior:

1. Install sbt 1.2.8 and metals-vscode 1.5.2.
2. Create a new project with `sbt new scala/scala-seed.g8`.
3. Open the new project in VS Code.
4. Open `build.sbt`.
5. Attempt to Ctrl+click on `Dependencies` on the first line. Nothing happens.
6. Place the cursor in the middle of `Dependencies`.
7. Press Ctrl+Space. Observe that completions are of the “abc” kind only.
8. Open `src/main/scala/example/Hello.scala`.
9. Ctrl+click on `println`. Observe that it goes to the definition of that symbol.

**Expected behavior**

There should be smart completions and go-to-definition, even in `build.sbt`.

**Installation:**

- Operating system: Debian sid, Linux, amd64
- VSCode version: VSCodium 1.36.1
- VSCode extension version: 1.5.2
- Metals version: 0.7.0

**Comment by tgodzik** [comment]
This will be done in this task https://github.com/scalameta/metals/issues/669
