### ISSUE TITLE
Any way to avoid opening Output panel?

### ISSUE THREAD

**Issue by fedragon** [scalameta/metals-vscode#137]
Hi,

I was wondering if there is any way to prevent Metals from opening the Output panel (and closing it right after) whenever it is running. The reason is that I usually keep a terminal open while developing (to run tests etc) and this behavior forces me to re-open it every time.

Thanks in advance!

**Comment by tgodzik** [comment]
It's being done automatically here: https://github.com/scalameta/metals-vscode/blob/master/src/extension.ts#L506

It does annoy me that it closes automatically, I see a couple of options, but best would most likely be to use show(preserveFocus?: boolean): void with preserveFocus set to true and if there is an active terminal open or Metals was open before, then let's not close it.

@olafurpg @gabro Any opinions?

**Comment by olafurpg** [comment]
Thank you for reporting! I can imagine this is annoying behavior if you have an open terminal window. I personally use a separate application for the terminal so the current behavior is not a problem.

I'm open to merge a change that avoids the opened output channel given that the current behavior remains unchanges for who don't have an open terminal window. Contributions are welcome!

**Comment by olafurpg** [comment]
There's a new `quietLogs` flag 

https://github.com/scalameta/metals/blob/90bc4909124b110dd5012ec0a1d1e72123017dab/metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageClient.scala#L90

that when true, will prevent the VS Code extension from opening the output panel. This flag is currently always false when running "import build" but we could discuss having some option to always set it to true.

**Comment by fedragon** [comment]
@olafurpg Awesome! Thanks a lot for following up on this!

**Comment by rmsam** [comment]
Hi all,

Apologies, but I didn't understand if we can already set this `quietLogs`flag's value or if this was a proposal for a way to add this functionality to vscode.

If possible to set, could advise on any documentation I could read on how to set it?

Thanks!

**Comment by tgodzik** [comment]
> Hi all,
> 
> Apologies, but I didn't understand if we can already set this `quietLogs`flag's value or if this was a proposal for a way to add this functionality to vscode.
> 
> If possible to set, could advise on any documentation I could read on how to set it?
> 
> Thanks!

@rmsam I totally forgot to respond here, sorry! This needs to be changed inside the extension - should be a simple fix. I will have some time in January to take a look, but anyone is welcome to work on it before then.

**Comment by Dan-Albrecht** [comment]
I have the exact opposite problem. I'm constantly annoyed that it randomly decides to close itself all the time. Wouldn't the ideal fix for everyone simply be, 'don't muck with it at all' (i.e. if it's already open, leave it open; if it's already closed, leave it close).

**Comment by phdoerfler** [comment]
> This flag is currently always false when running "import build" but we could discuss having some option to always set it to true.

I would very much appreciate an option to keep the metals output panel from showing when running "import build".

**Comment by tgodzik** [comment]
Fixed by https://github.com/scalameta/metals-vscode/pull/336
