### ISSUE TITLE
Metals prompts for custom java 8 setting even if java 11 is available

### ISSUE THREAD

**Issue by bjornregnell** [scalameta/metals-vscode#139]
**Describe the bug**

On OpenJDK11 under Ubuntu 18.04, Metals for VS Code v 1.5.2 prompts for Java 8 and suggests to provide path to Java 8 in settings, BUT release notes already for 1.5.0 said "upgrade to 0.7.0" claiming support for Java 11 https://scalameta.org/metals/blog/2019/06/28/thorium.html

**To Reproduce** Steps to reproduce the behavior:

1. Install OpenJDK on Ubuntu
2. Import a build
3. The prompt is shown for missing Java 8 with a tip to set javahome manually
"Unable to find Java 8 home. To fix this problem, update the 'Java Home' setting to point to a Java 8 home directory"

**Expected behavior**
Metals should just work with Java11 available 
- Operating system: Tested on Ubuntu both 18.04 and 16.04 with OpenJDK11
- VSCode version: 1.37
- VSCode extension version: 1.5.2
- Metals version: 0.7.0

**Search terms**

Metals Java 11 support

**Comment by olafurpg** [comment]
Thank you for reporting! Should be fixed in #154, we'll try to release a new version soon
