### ISSUE TITLE
Code Highlighting broken if the word `schema` is used in s-string

### ISSUE THREAD

**Issue by BalduinLandolt** [scalameta/metals-vscode#1397]
**Describe the bug**

Code highlighting is broken if an s-string contains the word "schema".

**To Reproduce** Steps to reproduce the behavior:

1. create any scala file
2. add scala code
3. add an s-string with the word "schema" (case sensitive!) in it
4. look at syntax highlighting after the s-string containing "schema"

**Expected behavior**

A string should be able to contain any word (ignoring special characters like quotation mark or backslash)

**Screenshots**

all ok with "Schema" (upper case) 

![image](https://github.com/scalameta/metals-vscode/assets/33053745/c9bee721-93f0-4342-b2b3-c37ecdf16aac)

broken highlighting with "schema" (lower case)

![image](https://github.com/scalameta/metals-vscode/assets/33053745/69fca455-275b-440a-bb39-e1c009ac8902)

**Installation:**

- Operating system: macOS
- VSCode version: 1.79.2
- VSCode extension version: 1.23.0
- Metals version: 0.11.12

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! I am unable to reproduce your issue:

![Screenshot from 2023-06-19 15-25-37](https://github.com/scalameta/metals-vscode/assets/3807253/8c792d8a-543c-44bb-98fe-b0ccd43f47da)

could this be caused by another extension? Are you using semantic highlighting?

**Comment by BalduinLandolt** [comment]
hm... must have been an extension conflict indeed. I created a separate profile with only scala-related and general purpose extensions, and now it's gone. Very weird, though, because none of my extensions should have caused this.  
In any case, sorry for the false alarm. I'll close this.

**Comment by tgodzik** [comment]
> hm... must have been an extension conflict indeed. I created a separate profile with only scala-related and general purpose extensions, and now it's gone. Very weird, though, because none of my extensions should have caused this. In any case, sorry for the false alarm. I'll close this.

No worries! It's really curious why this happens, let us know if you ever figure it out!
