### ISSUE TITLE
Mill 0.11.1 Bloop fails

### ISSUE THREAD

**Issue by hmf** [scalameta/metals-vscode#1403]
**Describe the bug**

The Bloop command that executes for Mill 0.11.1 fails due to changes in the imports.  

**To Reproduce** Steps to reproduce the behavior:

1. Setup a mill project  
2. In the `.mill-version` file set the Mill version to 0.11.1
3. Open the VSCode IDE in the project root. If it asks to load the Mill project, say yes.
4. Looking at the logs we see an error. The equivalent command is:

```shell
./millw --mill-version 0.11.1 --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.Bloop/install
[build.sc] [44/49] cliImports 
Cannot resolve external module mill.contrib.Bloop
 ```

**Expected behavior**

I would expect the command to execute with no problems. The issue is the bloop class name has now changed. The [following command](http://mill-build.com/mill/contrib/bloop.html) works fine:

```shell
./mill --import ivy:com.lihaoyi::mill-contrib-bloop:  mill.contrib.bloop.Bloop/install
```
Note that the import is the same, but the class is not. 

**Screenshots**

No screenshots.

**Installation:**

- Operating system: Linux (Ubuntu) X64 5.19.0-46-generic
- VSCode version: 1.79.2
- VSCode extension version: cannot find it
- Metals version: (found in VSCode settings, under `metals.serverVersion`) 0.11.12

**Additional context**

Possible recent change to Mill, so I don't know if it is supported yet by Metals.  

**Search terms**

mill bloop 0.11 mill-contrib-bloop

**Comment by tgodzik** [comment]
Thanks for reporting! This is already fixed in the latest snapshot and a full release should be out tomorrow!
