### ISSUE TITLE
Metals have been kept in the service stage

### ISSUE THREAD

**Issue by KONEONE** [scalameta/metals-vscode#1410]
I tried to use VSCODE to remotely develop the SCALA project, so install Metals, but it has been in the opening service stage. I have tried to reinstall it, but it has no effect.

metals version ： 1.24.0

![Uploading image.png…]()

**Comment by tgodzik** [comment]
Thanks for reporting! Could you provide some more details. How did you install Metals? What do you use for remote connection?

The image seems to have failed to upload also (you might have clicked too soon)
