### ISSUE TITLE
Can't download metals0.7.5

### ISSUE THREAD

**Issue by xiligey** [scalameta/metals-vscode#144]
It prints the follow log for 30 minutes and doesn't change anything. How to fix it ?

Still downloading:
https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.7.5/metals_2.12-0.7.5.jar (30.30 %, 954533 / 3150428)
https://repo1.maven.org/maven2/org/scalameta/mtags_2.12.9/0.7.5/mtags_2.12.9-0.7.5.jar (11.16 %, 180026 / 1613427)
Still downloading:
https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.7.5/metals_2.12-0.7.5.jar (30.30 %, 954533 / 3150428)
https://repo1.maven.org/maven2/org/scalameta/mtags_2.12.9/0.7.5/mtags_2.12.9-0.7.5.jar (11.16 %, 180026 / 1613427)
Still downloading:
https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.7.5/metals_2.12-0.7.5.jar (30.30 %, 954533 / 3150428)
https://repo1.maven.org/maven2/org/scalameta/mtags_2.12.9/0.7.5/mtags_2.12.9-0.7.5.jar (11.16 %, 180026 / 1613427)
Still downloading:
https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.7.5/metals_2.12-0.7.5.jar (30.30 %, 954533 / 3150428)
https://repo1.maven.org/maven2/org/scalameta/mtags_2.12.9/0.7.5/mtags_2.12.9-0.7.5.jar (11.16 %, 180026 / 1613427)

**Comment by tgodzik** [comment]
Looks like this was just some connection mishap. Closing for now.
