### ISSUE TITLE
Bug 🐛🐛🐛🐛🐛    cannot debug simple scala program and its not compiled and not genrate .scala-build

### ISSUE THREAD

**Issue by ECEAthipanbose** [scalameta/metals-vscode#1458]
To Reproduce:

Open VSCode.
Open an empty folder (let's call it "A5").
Create a src folder inside the "A5" folder.
Inside the src folder, create a main subfolder.
Create a Sample.scala file inside the main subfolder.
Paste some sample Scala code into Sample.scala.
Observe that the .scala-build directory is not generated, and the Scala file is not compiled.
Expected behavior:

The .scala-build directory should be generated automatically by the Metals extension.
The Scala file (Sample.scala) should be compiled, allowing you to debug the sample code. and show the run|debug on main method

**Comment by tgodzik** [comment]
Thanks for reporting! When I follow you instructions everything works fine, do you get any errors in your logs?

**Comment by ECEAthipanbose** [comment]
2024.02.17 19:57:27 WARN  no build tool detected in workspace 'path/to/A6'. The most common cause for this problem is that the editor was opened in the wrong working directory, for example if you use sbt then the workspace directory should contain build.sbt. 
2024.02.17 19:57:27 WARN  Build server is not auto-connectable.
2024.02.17 19:57:50 INFO  no build target found for 'path/to/A6/Sample.scala'. Using presentation compiler with project's scala-library version: 3.3.1
2024.02.17 19:57:50 WARN  Could not find semantic tokens for: 'path/to/A6/Sample.scala'
2024.02.17 19:57:50 INFO  time: code lens generation in 2.27s
2024.02.17 19:59:59 WARN  Could not find semantic tokens for: 'path/to/A6/Sample.scala'
2024.02.17 20:00:10 WARN  Could not find semantic tokens for: 'path/to/A6/Sample.scala'
2024.02.17 20:00:29 WARN  no build target for: 'path/to/A6/Sample.scala'
2024.02.17 20:01:04 WARN  no build target for: 'path/to/A6/Sample.scala'
Feb 17, 2024 8:02:03 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 69
2024.02.17 20:02:04 WARN  no build target for: 'path/to/A6/Sample.scala'

![Screenshot from 2024-02-17 20-02-17](https://github.com/scalameta/metals-vscode/assets/114050238/d55d48d1-0c4a-4234-9cd1-9530da083c15)

**Comment by tgodzik** [comment]
Could you show the full log? Also what is you Metals version?

**Comment by ECEAthipanbose** [comment]
metals version 1.2.0+12-644090c2-SNAPSHOT

**Comment by tgodzik** [comment]
Could you check out the latest version? That's `1.2.2+27-c7759e1e-SNAPSHOT` or just latest stable `1.2.2`

**Comment by ECEAthipanbose** [comment]
yeah work but rare time the same problem occur and tell no build target found in orkspace 

there is any option to manually compile my whole workspace ?

**Comment by tgodzik** [comment]
You can always just use Scala CLI itself by running `scala-cli setup-ide .` in the workspace root
