### ISSUE TITLE
No metals symbol on sidebar, can't start metals.

### ISSUE THREAD

**Issue by futurehome** [scalameta/metals-vscode#1467]
Type: <b>Bug</b>

After installing metals extension, there is no symbol listed in the tools sidebar of vscode.

Extension version: 1.29.0
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (4 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.71GB (0.82GB free)|
|Process Argv|--crash-reporter-id d5cb2b83-34fd-454b-9a53-fb2c968d48a2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (4 x 2419)|
|Memory (System)|3.68GB (2.98GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30973184
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
bg6jg535:30958357
dsvsc020cf:30973509
jchc7451:30973076

```

</details>

**Comment by futurehome** [comment]
Like this.
![image](https://github.com/scalameta/metals-vscode/assets/6230304/4f22a701-f16b-4b96-8ce6-b76b6d62e031)

**Comment by tgodzik** [comment]
Looks like it's not enabled for WSL. The Metals icon should show up even if the server didn't start.

**Comment by futurehome** [comment]
It's already enabled.
![image](https://github.com/scalameta/metals-vscode/assets/6230304/6da95f78-6962-4fa8-9431-253b8ae97a0a)

**Comment by futurehome** [comment]
And there is no reponse when clicking the "new scala project" and "start metals".
![image](https://github.com/scalameta/metals-vscode/assets/6230304/28152366-09f6-40e7-9208-1d463a77f2b4)

**Comment by tgodzik** [comment]
How did you get to the panel if it's not available in the tabs? Do you get any information about why the server doesn't start in the Metals output window?

**Comment by futurehome** [comment]
When hovering mouse over there, it show the name "metals", then I know it's there, and I can click it to get to the panel. 

How can I get the information of Metals? I find nothing about Metals in the Output.

**Comment by futurehome** [comment]
Looks like Metals has some confilct with WSL, if I disable WSL remote, the Metals symbol appears on the panel.

**Comment by futurehome** [comment]
I re-install metals after connecting to WSL, everything works now. 
Thanks.
