### ISSUE TITLE
Clean up ANSI escape codes from downloading logs 

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals-vscode#153]
Follow up on https://github.com/scalameta/metals-vscode/pull/149#issuecomment-541611856

**Comment by olafurpg** [comment]
@alexarchambault is there a way to prevent the ansi escape codes using the latest coursier when running `fetch`?
```
�[2KDownloaded 1 missing file(s) / 8
```
We recently upgraded to 2.0.0-RC3-4 from an older version that did not have these escape codes.

**Comment by alexarchambault** [comment]
https://github.com/coursier/coursier/pull/1420 should fix that.

**Comment by alexarchambault** [comment]
Ah, that must be have been made worse because the launcher now downloads multiple files…

**Comment by olafurpg** [comment]
Thank you!

**Comment by tgodzik** [comment]
Checked and this is now fixed! :tada:
