### ISSUE TITLE
Import Build not importing build

### ISSUE THREAD

**Issue by TheAndrewFranklin** [scalameta/metals-vscode#157]
**Describe the bug**

I don't think it's a bug. I think it's something I'm doing wrong, but I've read A LOT of your docs and still can't figure it out:

Extension installs just fine, but does not attempt to import build when I open my build.sbt file, nor if I press `Import Build`

**To Reproduce** Steps to reproduce the behavior:

1. Go to Metals Tab
2. Click on Import Build
3. Quick flicker, then nothin'

**Expected behavior**

It should install something or something, right?

**Comment by olafurpg** [comment]
Thank you for reporting! Can you please describe your build structure and include the output from the “.metals/metals.log” file?

**Comment by tgodzik** [comment]
Closing this one since we don't have anything to go on here.
