### ISSUE TITLE
Use custom icon for worksheet files

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals-vscode#162]
Currently, `*.sc` files don't have any icon.

<img width="903" alt="Screenshot 2019-11-13 at 23 25 59" src="https://user-images.githubusercontent.com/1408093/68835491-11ea6f80-066d-11ea-9b41-bc392d02c190.png">

It would be nice if those files had some icon that resembled the Scala icon but was still distinct.

**Comment by tgodzik** [comment]
@olafurpg what do you think about:
![image](https://user-images.githubusercontent.com/3807253/73738390-b0eea700-4744-11ea-98fa-3802a034ea82.png)

**Comment by olafurpg** [comment]
Hmm, what is the icon supposed to mean? I was thinking it could be clearer with something like `>` 🤔

**Comment by tgodzik** [comment]
It's a looking glass over some ticks, which would mean we are looking into the results of evaluations.
Maybe we can make the looking glass not vertical and use `>`

**Comment by tgodzik** [comment]
What about:

- dark theme
![icon (1)](https://user-images.githubusercontent.com/3807253/73762203-27ed6500-4770-11ea-83be-b03f99465284.png)
- light theme
![icon_lt](https://user-images.githubusercontent.com/3807253/73762206-291e9200-4770-11ea-9c94-07ab04971026.png)

**Comment by olafurpg** [comment]
I'm liking that direction, but I think it might still be nicer with a slightly simpler logo and giving a bit more space for the Scala background. Any thoughts @gabro @ckipp01 ?

**Comment by gabro** [comment]
I like the direction of a prompt + the Scala logo. I’m not sure the magnifying lens is necessary, I would need to see this in the editor to have a better feel.

Also, what about losing the gradient on the logo so that the icon is more aligned with the regular one?

**Comment by ckipp01** [comment]
Yea I guess my initial thought is that I'd just leave out the magnifying glass and keep the `>`.

**Comment by tgodzik** [comment]
That's how it currently looks:

![image](https://user-images.githubusercontent.com/3807253/73834481-178ac800-480c-11ea-8d00-c14e6f591ba5.png)

![image](https://user-images.githubusercontent.com/3807253/73834485-1c4f7c00-480c-11ea-92b7-a2d1f1f05bb1.png)

Might be good to actually lose the gradient and the magnifying glass. I working on this with our graphic designer in any case, I am not that good at icons haha.

**Comment by tgodzik** [comment]
So, I did dig around this and it's actually not easy to add a single icon because of: https://github.com/Microsoft/vscode/issues/14662

That said, you can use for example https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme or similar to get an icon for any `.sc` files. This will be the default Scala icon, but I think it's perfectly fine and especially with such a large number of possible extensions it doesn't make sense to try to add a new icon everywhere.

**Comment by Sporarum** [comment]
What is the situation right now, I don't have an icon on my `.worksheet.sc` files, is this expected or a bug ?

I found this, I don't know how it affects the situation:
https://github.com/microsoft/vscode/issues/140047

**Comment by tgodzik** [comment]
I think we can now do:
```

      {
        "id": "scala",
        "extensions": [
          ".worksheet.sc"
        ],
        "icon": {
          "dark": "icons/worksheet-dark.png",
          "light": "icons/worksheet-light.png"
        }
      },
```

in metals, but it seems to work weird and makes that the default for any Scala file irrelevant if the extension fits. Setting a different language id makes it stop being recognized as Scala altogether. So probably we should just use the default icon for Scala, contribute one to icon themes or add the base config to vscode-scala-syntax repo

**Comment by tgodzik** [comment]
Ach also:
```
No, we just allow to set a single language icon.
```
so the only way we can improve the situation is to add default scala to all possible extensions inside the vscode scala syntax plugin https://github.com/scala/vscode-scala-syntax
