### ISSUE TITLE
Custom repositories for fetching Coursier are not picked up

### ISSUE THREAD

**Issue by DieBauer** [scalameta/metals-vscode#173]
This looks like its related to #126, but since that one is closed, I've opened a new one. 

Using Metals in VSCode: 
I have set the `Metals: Custom Repositories` but these are not picked up by the coursier fetching itself: 

I know I have a MITM corporate proxy which should never be used for this. And I want it to pick up my internal Maven Repository, but Maven.org is always used, no matter what I put in the aforementioned setting. 

```
Error while downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-publish_2.12/2.0.0-RC5-3/coursier-publish_2.12-2.0.0-RC5-3.jar: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, ignoring it
Error while downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.12/2.0.0-RC5-3/coursier-cache_2.12-2.0.0-RC5-3.jar: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, ignoring it
Error while downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-install_2.12/2.0.0-RC5-3/coursier-install_2.12-2.0.0-RC5-3.jar: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, ignoring it
Error while downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.12/2.0.0-RC5-3/coursier-cli_2.12-2.0.0-RC5-3.jar: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, ignoring it
```

Used version:
```
Name: Scala (Metals)
Id: scalameta.metals
Description: Scala language server with rich IDE features
Version: 1.7.1
Publisher: Scalameta
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=scalameta.metals
```

**Comment by gabro** [comment]
@DieBauer thanks for reporting!

Have you tried setting the `COURSIER_REPOSITORIES`  env variable and then launching VS Code from the command line?

**Comment by DieBauer** [comment]
```sh
> export COURSIER_REPOSITORIES="mycustomrepo"
> code .
``` 
This starts VSCode with `COURSIER_REPOSITORIES` set. 

When I start a terminal embedded in VSCode: 
```sh
code> echo $COURSIER_REPOSITORIES
mycustomrepo
```

But Metals still fails with the same message, maven.org.

**Comment by tgodzik** [comment]
`COURSIER_REPOSITORIES` will not help here, cousier can use maven mirror, but  I am not 100% sure how to do that. It would good to document it on the website. 

It was added here: https://github.com/coursier/coursier/pull/1429

**Comment by tgodzik** [comment]
From what I see we need to specify `COURSIER_MIRRORS` set to a file with a proper mirror configuration. From the website:

```
Mirrors
coursier got support for mirrors, kind of like Maven has. Mirrors allow to substitute some repositories for others. This can be useful with internal Maven repositories mirroring Maven Central for example. In that case, you'd prefer requests to go to that mirror rather than to Maven Central.

Mirrors are automatically picked from the API (unless explicitly disabled) and the CLI.

They can be configured via configuration files, namely ~/.config/coursier/mirror.properties on Linux, and ~/Library/Preferences/Coursier/mirror.properties on OS X. For example, these settings allow to replace Maven Central with JCenter

jcenter.from=https://repo1.maven.org/maven2
jcenter.to=https://jcenter.bintray.com
Mirrors should be described in more detail in the coursier documentation in a later time.
```

We could try to set the properties and maybe if that doesn't work use the environment variable?

**Comment by DieBauer** [comment]
That sounds like the correct key. However I couldn't reproduce this with:

```sh
>export COURSIER_MIRRORS="jcenter.from=https://repo1.maven.org/maven2
jcenter.to=mycustomrepo"
>echo $COURSIER_MIRRORS
jcenter.from=https://repo1.maven.org/maven2
jcenter.to=mycustomrepo
```

However VSCode metals does not pick this up. (even though this commit suggests otherwise? https://github.com/scalameta/metals-vscode/commit/b7201d19d5d7bd65df3b20fe05621c052e8fc29b )

And it looks to me that all `env` are added to the process (https://github.com/scalameta/metals-vscode/blob/master/src/extension.ts#L179) 

Do you have any clue how to test this?

**Comment by tgodzik** [comment]
> That sounds like the correct key. However I couldn't reproduce this with:
> 
> ```shell
> >export COURSIER_MIRRORS="jcenter.from=https://repo1.maven.org/maven2
> jcenter.to=mycustomrepo"
> >echo $COURSIER_MIRRORS
> jcenter.from=https://repo1.maven.org/maven2
> jcenter.to=mycustomrepo
> ```
> 
> However VSCode metals does not pick this up. (even though this commit suggests otherwise? [b7201d1](https://github.com/scalameta/metals-vscode/commit/b7201d19d5d7bd65df3b20fe05621c052e8fc29b) )
> 
> And it looks to me that all `env` are added to the process (https://github.com/scalameta/metals-vscode/blob/master/src/extension.ts#L179)
> 
> Do you have any clue how to test this?
> 
> EDIT: Or is it this https://github.com/scalameta/metals-vscode/blob/master/src/extension.ts#L239 line that does the env propagation to the coursier binary?

I would try to do it via `mirror.properties` - only specified env variables are added when running cousier.

**Comment by DieBauer** [comment]
Mm, can't seem to make it work... 

Found this one: https://github.com/coursier/coursier/issues/1341 that sounds like what I'm experiencing. If that's the case, then I guess it's a wontfix.

**Comment by tgodzik** [comment]
This should be fixed by https://github.com/coursier/coursier/pull/1429, so this should work currently
Where are you creating the `mirror.properties` ? Maybe it's the wrong place?

**Comment by tgodzik** [comment]
```
Cousier uses https://github.com/soc/directories-jvm, so the config directory should be something like:
// Lin: /home/alice/.config/cousier
// Mac: /Users/Alice/Library/Preferences/Cousier
// Win: C:\Users\Alice\AppData\Roaming\Coursier\config
```

**Comment by DieBauer** [comment]
Yes you are right. The environment variable COURSIER_MIRRORS should contain the location of the file, not the contents of the file. 
So even though I had set the contents as described in the docs in `~/Library/.config/coursier/mirror.properties`, the environment variable was wrong. 

After unsetting it, the default `mirror.properties` is picked up! 

Thanks for your support :) 

Not sure what the best approach is for this. I think linking to `https://get-coursier.io/blog/index.html#mirrors` would help.

**Comment by tgodzik** [comment]
Added documentation for this kinds of issues: https://scalameta.org/metals/docs/build-tools/proxy.html
