### ISSUE TITLE
Artifacts not published to GitHub releases

### ISSUE THREAD

**Issue by sideeffffect** [scalameta/metals-vscode#184]
The releases pages on GitHub, eg
https://github.com/scalameta/metals-vscode/releases/tag/v1.7.0
https://github.com/scalameta/metals-vscode/releases/tag/1.7.2
don't contain the build artifact, like `scalameta.metals-1.7.2.vsix`, uploaded and viable there

the `vsix` file is only available via Microsoft's Marketplace
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/scalameta/vsextensions/metals/1.7.2/vspackage

That is not a viable source for other IDEs.
The `vsix` files have to be available somewhere else, GitHub releases is probably the best place, so that Metals is officially included in Eclipse Che web IDE.
https://github.com/eclipse/che-plugin-registry/pull/356

Related issue: https://github.com/scala/vscode-scala-syntax/issues/75

**Comment by tgodzik** [comment]
Also @sideeffffect do you know any examples of automation of this process?

**Comment by tgodzik** [comment]
In the meantime I added the extension to the most recent release : https://github.com/scalameta/metals-vscode/releases/tag/1.7.2

**Comment by sideeffffect** [comment]
Since you're using Travis, is should be relatively easy
https://docs.travis-ci.com/user/deployment/releases/

**Comment by sideeffffect** [comment]
> I added the extension to the most recent release

thanks! :+1: for simplicity's sake, it would be best, if the file names on GitHub releases and Microsoft marketplace matched 100%. Could you please rename it on GitHub releases from `metals-1.7.2.vsix` to `scalameta.metals-1.7.2.vsix`?

**Comment by tgodzik** [comment]
@sideeffffect fixed!

**Comment by gabro** [comment]
The CI now takes care of this 🎉
