### ISSUE TITLE
Failed to download Metals on MacOS

### ISSUE THREAD

**Issue by Hurtak** [scalameta/metals-vscode#187]
**Describe the bug**

After I install extension from the marketplace I get the following error

```
Failed to download Metals, make sure you have an internet connection and the Java Home '/usr/libexec/java_home -v 1.8/bin/java' is valid. You can configure the Java Home in the settings.See https://scalameta.org/metals/docs/editors/vscode.html#http-proxy for instructions if you are using an HTTP proxy.
```

**Installation:**

- Operating system: MacOS 10.15.2
- VSCode version: 1.41.1
- VSCode extension version: 1.7.2
- Metals version: none?

**Additional context**

- I have internet connection
- I have Java Home set, (sbt and scala works as expected)
- I am not behind proxy

`/usr/libexec/java_home -v 1.8/bin/java`
returns
`/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home`

`echo $JAVA_HOME`
returns
`/usr/libexec/java_home -v 1.8`

`java -version`
returns
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
````

**Comment by tgodzik** [comment]
Thanks for reporting! Have you tried reloading the window? It will redownload the Metals server.

If that still doesn't work, would it be possible for you to paste the logs from ./.metals/metals.log ?

**Comment by olafurpg** [comment]
@Hurtak what is the value of the Java home setting for you? What happens if you set it to ` /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home`?

**Comment by olafurpg** [comment]
Judging by the error message, it looks like the Java home setting is currently configured to "/usr/libexec/java_home -v 1.8/bin/java", which is not a valid Java home path.

**Comment by Hurtak** [comment]
@olafurpg you are right, I had the command, not the output of the command stored in the JAVA_HOME. After fixing it, it works correctly now. Thanks for the help.

**Comment by modsoussi** [comment]
Also seeing this error, even though it seems my JAVA_HOME is set correctly.

- macOS: 10.14.6
- VS Code version: 1.43.2
- VS Code extension version: 1.8.5

This is what VS Code gives me:
```
Failed to download Metals, make sure you have an internet connection and the Java Home '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home' is valid. You can configure the Java Home in the settings.See https://scalameta.org/metals/docs/editors/vscode.html#http-proxy for instructions if you are using an HTTP proxy.
```

I am also seeing the following error output:
```
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
Error while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend/emoji_2.12/1.2.1/jars/emoji_2.12.jar: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, ignoring it
```.

**Comment by tgodzik** [comment]
@modsoussi Looks like an issue with SSL. Not sure where it might coming from, maybe try to remove that path and reload? Please report a new issue if that doesn't help.

**Comment by modsoussi** [comment]
@tgodzik removed the path and reloaded and still same error. Opening a new issue!

**Comment by modsoussi** [comment]
@tgodzik I reinstalled the jdk and now everything's working!
