### ISSUE TITLE
metals not activated

### ISSUE THREAD

**Issue by zhenleibb** [scalameta/metals-vscode#213]
**Describe the bug**
Metals isn't activated when I open the file *.sbt or *.scala. 
When I launch manually a command of metals, the notification display command not found. 

**To Reproduce**
1. in terminal:

```
  mkdir foo-build
  cd foo-build
  touch test.scala
```
2. open `test.scala` with vscode.
3. `Ctrl + Shift + P`; run command `Metals:run doctor`
4. See error `command 'metals.doctor-run' not found`

**Expected behavior**
When I open  `test.scala`, it should to prompt me to import the build.
When I run command `Metals:run doctor`, the notification should not display the error  command not found.

**Installation:**
- Operating system: Ubuntu 18.04.3 LTS
- Editor: Visual Studio Code
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-76-generic
- Metals version:1.7.8
- extension enabled globally in vscode: 
Scala(Metals) 1.7.8
Scala syntax (official) 0.3.9
I don't have extensions Scala Language Server and Scala (sbt) installed

**Additional context**
I have installed metals in emacs, it runs without problems. So I think my installation of metals does not have problems.
I have also installed python in vscode. It runs. So I think the problem no from vscode in its globality. The problem is from metals-vscode.

**Comment by tgodzik** [comment]
Metals should be activated automatically in `sbt` workspaces. Could you copy the log from `Log (Extension Host)` - it should be available in the `Output`- and paste in the comment here?

It might have some relevant information on why the extension was not started.

**Comment by zhenleibb** [comment]
I thought the problem maybe is my `sbt` workspace no is correct, even if metals-emacs can run with it. 
So I have opened vscode in a new more correct `sbt` workspace. But it still doesn't run.

**To Reproduce**
```
#!/bin/sh
mkdir -p src/{main,test}/{java,resources,scala}
mkdir lib project target

# create an initial build.sbt file
echo 'name := "MyProject"
version := "1.0"
scalaVersion := "2.10.0"' > build.sbt
```
open `build.sbt` with vscode.
**Behavior of vscode**
Metals still isn't activated.
Log (Extension Host):
> [2020-02-21 21:50:48.809] [exthost] [info] extension host started
> [2020-02-21 21:50:49.141] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
> [2020-02-21 21:50:49.141] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
> [2020-02-21 21:50:49.298] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
> [2020-02-21 21:50:49.298] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/emmet/dist/extension
> [2020-02-21 21:50:49.364] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.git","_lower":"vscode.git"},"activationEvent":"*"}
> [2020-02-21 21:50:49.364] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/git/dist/main
> [2020-02-21 21:50:49.475] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
> [2020-02-21 21:50:49.475] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/merge-conflict/dist/extension
> [2020-02-21 21:50:49.546] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
> [2020-02-21 21:50:49.546] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/search-result/dist/extension.js
> [2020-02-21 21:50:49.570] [exthost] [info] ExtensionService#_doActivateExtension vscode.vscode-account {"startup":true,"extensionId":{"value":"vscode.vscode-account","_lower":"vscode.vscode-account"},"activationEvent":"*"}
> [2020-02-21 21:50:49.570] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/vscode-account/dist/extension.js
> [2020-02-21 21:50:49.625] [exthost] [info] ExtensionService#_doActivateExtension scalameta.metals {"startup":false,"extensionId":{"value":"scalameta.metals","_lower":"scalameta.metals"},"activationEvent":"onLanguage:scala"}
> [2020-02-21 21:50:49.625] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/zhenlei/.vscode/extensions/scalameta.metals-1.7.8/out/extension
> [2020-02-21 21:50:55.107] [exthost] [info] eager extensions activated

**Comment by tgodzik** [comment]
I tested your script and the Metals extension is activated and from the logs it looks like it is activated in your workspace too. 

Your script is still missing information about the sbt version that should be in:
```
./project/build.properties
sbt.version=1.3.7
```
we will not be able to import the build without it.

**Comment by zhenleibb** [comment]
So metals-vscode doesn't work like metals-emacs? Because my emacs can run metals-emacs without this line in  `./project/build.properties`.

I have thought that metals-vscode no prompts me to import the build when I open `build.sbt`, and it displays command not found when I run a metals command, because metals-vscode isn't activated.
But after I add the line `sbt.version=1.3.7` in `./project/build.properties`, it still can't find the metals commands. For instance, when I run command `Metals:run doctor` .

So the problem is from another place.

**Comment by tgodzik** [comment]
> So metals-vscode doesn't work like metals-emacs? Because my emacs can run metals-emacs without this line in ./project/build.properties.

It works the same time in `metals-emacs` we need information about the sbt version to run the import.

> So the problem is from another place.

Did you manage to run the build import? Is there anything in the logs? Could you check `Output (Metals)` and `.metals/metals.log` ? If there was anything indicating any issues it would be be helpful, since the workspace does work for me and I am unable to reproduce your issues.

**Comment by zhenleibb** [comment]
When I open `build.sbt`, metals don't produce the directory `.metals`. The server lsp isn't running.
```
$ ps -ax | grep metals
10551 ?        Sl     0:01 /usr/share/code/code --no-sandbox --unity-launch /home/zhenlei/tmp/metals/build.sbt
10752 pts/1    S+     0:00 grep --color=auto metals
```

But I don't know why you think metals is activated. Because in the log above, for every module, I have `"startup" : true`. Except for metals, I have `"startup" : false`
```
[2020-02-21 21:50:49.625] [exthost] [info] ExtensionService#_doActivateExtension scalameta.metals {"startup":false,"extensionId":{"value":"scalameta.metals","_lower":"scalameta.metals"},"activationEvent":"onLanguage:scala"}
[2020-02-21 21:50:49.625] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/zhenlei/.vscode/extensions/scalameta.metals-1.7.8/out/extension
```
So I think metals isn't activated.

And for additional information, the file `file:///home/zhenlei/.vscode/extensions/scalameta.metals-1.7.8/out/extension` no exists.

**Comment by tgodzik** [comment]
`"startup": false` only means that the extension is not activated on Visual studio Code startup, but that extension is activated now after detecting Scala.

If `file:///home/zhenlei/.vscode/extensions/scalameta.metals-1.7.8/out/extension` doesn't exist it means Visual Studio code didn't download it. Metals extension should be in that directory, it cannot be activated if it doesn't exists.

But that directory should exist otherwise there should be logs in `Logs (Extension Host)` about a missing directory. There might be some issues with downloading Metals, but information about that could be in `Output (Metals)`

**Comment by zhenleibb** [comment]
Yes, extensions of metals exist
```
$ ls /home/zhenlei/.vscode/extensions/scalameta.metals-1.7.8/out/
client-commands.js      extension.js    lazy-progress.js   protocol.js       treeview.js
decoration-protocol.js  installJava.js  MetalsFeatures.js  scalaDebugger.js  tree-view-protocol.js
```
Output(Metals) gives:
`Metals will not start because you've opened a single file and not a project directory.`

This means my sbt directory is incorrect, and vscode-metals can't recognize it?
```
$ ls -Ra
.:
.  ..  build.sbt  lib  project  src  target

./lib:
.  ..

./project:
.  ..  build.properties  .build.properties.swp

./src:
.  ..  main  test

./src/main:
.  ..  java  resources  scala

./src/main/java:
.  ..

./src/main/resources:
.  ..

./src/main/scala:
.  ..

./src/test:
.  ..  java  resources  scala

./src/test/java:
.  ..

./src/test/resources:
.  ..

./src/test/scala:
.  ..

./target:
.  ..
$ cat ./project/build.properties 
sbt.version=1.3.8
$ cat build.sbt
name := "MyProject"
version := "1.0"
scalaVersion := "2.12.7"
```

**Comment by tgodzik** [comment]
`Metals will not start because you've opened a single file and not a project directory.` 
It probably means you chose `File` -> `Open file`, which means we will not have the directory available just a file, which is not enough for Metals to work.

In order to work on a project you need to do:
`File` -> `Open folder` and chose the root of your workspace.

**Comment by zhenleibb** [comment]
It runs!Thank you!

I have done a stupid error. Habitually, I use emacs, I'm newbie in vscode. I don't know I should open the folder to launch the extension of a language.

**Comment by kyrsideris** [comment]
I had a similar problem. The prompt to check VSCode's logs in `Log (Extension Host)` did the trick. The plugin needed later VSCode version, for some reason the VSCode has stuck into an older version. It works fine after the update. Thanks!

**Comment by hellosayak** [comment]
After following "File -> Open folder" in vscode it has got activated for me. Thanks..!!
