### ISSUE TITLE
How to use a newer version of bloop plugin for sbt?

### ISSUE THREAD

**Issue by tigerinus** [scalameta/metals-vscode#215]
**Describe the bug**

When I import a build that replies on sbt 0.13.xx, I hit this bug https://github.com/scalacenter/bloop/issues/1158 during bloopInstall.

The issue is fixed in a newer unreleased version of bloop (1.4.0-RC1-64-96c8b667)

HOW I can make metals extension to use this newer version of bloop?

Thanks!

**To Reproduce** Steps to reproduce the behavior:

1. Open a project that relies on sbt 0.13.xx
2. Import build.

**Expected behavior**

Build is imported successfully

**Screenshots**

![image](https://user-images.githubusercontent.com/7172560/74704068-131dd080-524a-11ea-96a1-2a9b89988069.png)

**Installation:**

- Operating system: WSL (Windows + Remote on Debian within WSL)
- VSCode version: 

Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054

- VSCode extension version:
- Metals version: 1.7.8

**Additional context**

```
it:compileIncremental from it:bloopCompile ((bloop.integrations.sbt.Offloader) Offloader.scala:19)
```

**Search terms**

bloop, bloopinstall, offloader.scala

**Comment by tgodzik** [comment]
In latest snapshots it's possible to specify the Bloop version via setting: `metals.bloopVersion` and in 0.8.0 and older you can use `bloop.sbt.version` server property.

Also, most likely newest Metals snapshots already use Bloop version with that issue fixed.

**Comment by tigerinus** [comment]
> In latest snapshots it's possible to specify the Bloop version via setting: `metals.bloopVersion` and in 0.8.0 and older you can use `bloop.sbt.version` server property.
> 
> Also, most likely newest Metals snapshots already use Bloop version with that issue fixed.

By 'setting' you mean VSCode setting correct?

I did so:

![image](https://user-images.githubusercontent.com/7172560/74731505-0ff30680-5283-11ea-818f-927773247b41.png)

But the new metals.sbt generated still looks like

![image](https://user-images.githubusercontent.com/7172560/74731566-30bb5c00-5283-11ea-9705-fbcf951f1ef8.png)

**Comment by tgodzik** [comment]
You also need to change the server version to one of the recent snapshots: https://scalameta.org/metals/docs/editors/vscode.html#using-latest-metals-snapshot

**Comment by tgodzik** [comment]
For 0.8.0 the old property `bloop.sbt.version` is still ok.

**Comment by tigerinus** [comment]
> You also need to change the server version to one of the recent snapshots: https://scalameta.org/metals/docs/editors/vscode.html#using-latest-metals-snapshot

I've updated server version to `0.8.0+271-1cc1180d-SNAPSHOT`

But then I got this error

![Annotation 2020-02-18 193242](https://user-images.githubusercontent.com/7172560/74732566-79741480-5285-11ea-94e3-13f178d49651.png)

I don't see any error in the output though.

**Comment by tigerinus** [comment]
I randomly clicked on https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/metals_2.12/0.8.0+271-1cc1180d-SNAPSHOT/maven-metadata.xml.sha1 from the output and got 404.

**Comment by tgodzik** [comment]
Looks like that release is broken. Checking what's going on.

In the meantime you can use 0.8.0 and `-Dbloop.sbt.version=true` in the server properties.

**Comment by tgodzik** [comment]
I am able to run `0.8.0+271-1cc1180d-SNAPSHOT` and no issues with downloading.
