### ISSUE TITLE
Warn users if serverVersion is older than default

### ISSUE THREAD

**Issue by gabro** [scalameta/metals-vscode#23]
Reporting an idea from @olafurpg 

Given:

- a `metals.serverVersion` value containing a semver-compliant version
- a `metals.serverVersion` set to an older release than the default value

we should warn the user upon extension activation.

I would probably exclude SNAPSHOT versions from this check.

**Comment by olafurpg** [comment]
I think we can pre-process the version string by removing everything following a plus `+`, so `0.3.1+1+SNAPSHOT` becomes `0.3.1`.

**Comment by gabro** [comment]
Yeah, my point about `SNAPSHOT` is not technical. Do we want to warn users that have a `SNAPSHOT` version? Maybe it's annoying if you know what you're doing.

**Comment by olafurpg** [comment]
The most common use-case for SNAPSHOT is to try out a pending feature in `0.3.1+10-SNAPSHOT` so I think it would be nice to get a warning when the default version becomes `0.3.2`
