### ISSUE TITLE
Metals download problem

### ISSUE THREAD

**Issue by Bestduan** [scalameta/metals-vscode#230]
I have set JAVA_HOME to C:\Program Files\Java\jdk1.8.0_241 but the following error keeps coming up when metals downloads

Failed to download Metals, make sure you have an internet connection and the Java Home ' C:\Program Files\Java\jdk1.8.0_241' is valid. You can configure the Java Home in the settings.See https://scalameta.org/metals/docs/editors/vscode.html#http-proxy for instructions if you are using an HTTP proxy.

How do I fix it？

**Comment by tgodzik** [comment]
Hey, thanks for reporting! Is there any more information in the Metals log output?
Shortcut `Ctrl + K, Ctrl + H` and then choose Metals in the dropdown on the right.

Are you behind any kind of proxy? What is the exact path to java binary?

**Comment by Bestduan** [comment]
I'm sorry，there is no more information in the Metals log output，and I have set up the  proxy.
Can I download Metals in other ways?

**Comment by Bestduan** [comment]
![screenShot.png](https://i.loli.net/2020/03/18/EqOH4B6V5FZMfLK.png)

**Comment by Bestduan** [comment]
When I started downloading, I was able to download normally. After I quit once, I kept reporting errors

**Comment by tgodzik** [comment]
@Bestduan This might be an issue with the proxy setting. Coursier boostrap which we use needs to have mirror setup to download the right coursier dependencies at the start. You can take a look here for hints:
https://scalameta.org/metals/docs/build-tools/proxy.html

**Comment by tgodzik** [comment]
@Bestduan did you manage to figure out the issue?

**Comment by Bestduan** [comment]
> @Bestduan您是否能够找出问题所在？

When I install Maven, it will be fine

**Comment by tgodzik** [comment]
Ok,  closing this for now. We can reopen if you need any more help.
