### ISSUE TITLE
Can't escape code insights while using Vim emulation

### ISSUE THREAD

**Issue by ctataryn** [scalameta/metals-vscode#237]
**Describe the bug**

The insights balloon won't go away after it is invoked

**To Reproduce** Steps to reproduce the behavior:

*Note: if you think this issue would be better posted to the Vim extension, please let me know.*

In my case I started typing `(newSpeaker -> subs)` as soon as I typed the initial `(` for this return value I got a balloon pop up above my cursor explaining the type signature of `map`.  As I started typing, the balloon follows my cursor and gives other info.

The problem is, I can't get that balloon to go away by hitting the "esc" key, or any other key. I need to actually use my mouse which is pretty disruptive.

[Video of the problem](https://i.imgur.com/it9SBRN.gif)

**Expected behavior**

Escape key should cancel out the code insight balloon

**Screenshots**

See above.

**Installation:**

- Operating system: Windows 10 v1909
- VSCode version: 

> Version: 1.43.0 (system setup)
> Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
> Date: 2020-03-09T19:47:57.235Z
> Electron: 7.1.11
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.18363
> 

- VSCode extension version:

0.8.1

**Additional context**

- Vim extension version:
1.13.0

**Comment by ckipp01** [comment]
Hi @ctataryn, thanks for reporting.  It sounds like this may be more of an issue with [vscodevim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) or how you have it set up rather than an issue with the Metals VS Code extension. If possible, I'd see see if this issue persists while using vim mode for another language when doing a hover. If so, we can ensure it's not an issue with the Metals VS Code extension.

**Comment by olafurpg** [comment]
Thank you for reporting! This feature is called “signature help” and I have experienced the same issue. I don’t think it’s related to the vim bindings. 

My workaround has been to bind escape to hide the balloon (mirroring behavior in IntelliJ). I don’t think there is much we can do to fix this issue on the server side. The only solution I can think of would be to disable trigger characters for signature help but that would mean a lot of people wouldn’t discovery this feature exists.

**Comment by olafurpg** [comment]
I believe the default vscode shortcut to hide the balloon is shift escape.

**Comment by ctataryn** [comment]
@olafurpg Beautiful, thanks!  With the vim plugin disabled, `esc` works. With it enabled `shift-esc` works 👍
