### ISSUE TITLE
Metals breaks with Scala 2.12.11

### ISSUE THREAD

**Issue by kmatasflp** [scalameta/metals-vscode#238]
New version of scala 2.12 was released yesterday: https://github.com/scala/scala/releases/tag/v2.12.11

After updating my projects to 2.12.11 half of the metals stopped working and is telling me to "Upgrade to Scala 2.12.10 and run 'Build import' to enable code navigation."

Expected behaviour: Metals works with the new version of scala

OS: MacOS 10.15.3
Metals: 0.8.1
VSCode: 1.43.0

**Comment by tgodzik** [comment]
Thanks for reporting! We are working on providing support for 2.12.11, there is already a PR for that here: https://github.com/scalameta/metals/pull/1510

I would recommend using 2.12.10 until the new version with support for 2.12.11 is released

**Comment by tgodzik** [comment]
Scala 2.12.11 should work now with the current snapshot version `0.8.1+52-03d618e3-SNAPSHOT`, I will follow up with a full release.
