### ISSUE TITLE
Visual Studio Code no longer displays errors with Scala Metals 1.8.3

### ISSUE THREAD

**Issue by oharboe** [scalameta/metals-vscode#244]
**Describe the bug**

I need some guidance on how to report this as I can't find any symptoms or logs. Since this happens only in 1.8.3 and that release is ca. 1 hour old as of writing, perhaps other users will run into it too?

I no longer get error messages in VSCode when there's an error in my Scala code with Scala metals 1.8.3.

**To Reproduce** Steps to reproduce the behavior:

1. Upgrade to 1.8.3
2. Introduce an error in you scala code
3. Wait for it to compile
4. 0 errors indicated
5. downgrading to 1.8.2 fixes the problem.

**Expected behavior**

Errors should be displayed

**Screenshots**

**Installation:**

- Operating system: Linux
- VSCode version: 1.43.1
- VSCode extension version:  1.8.3
- Metals version: 0.8.3

**Additional context**
There are no error messages or supicious warnings in the logs.

```
INFO  logging to file /home/oyvind/ascenium/ascenium/hardware/aptos/.metals/metals.log
INFO  started: Metals version 0.8.3 in workspace '/home/oyvind/ascenium/ascenium/hardware/aptos'
INFO  time: initialize in 0.82s
Initializing Scala Debugger
INFO  skipping build import with status 'Installed'
INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/oyvind/.cache/metals/bsp.trace.json
INFO  time: connected to build server in 0.21s
INFO  Connected to Build server v1.4.0-RC1-105-118a551b
INFO  compiling aptos (1 scala source)
INFO  time: compiled aptos in 0.68s
WARN  Could not find java sources in Some(/usr/lib/jvm/java-11-openjdk-amd64/). Java symbols will not be available.
INFO  time: indexed workspace in 3.17s
INFO  compiling aptos (1 scala source)
INFO  time: compiled aptos in 0.4s
```

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! I can confirm it's happening and checking what is going on. You can revert to metals server version 0.8.1 for the time being.

**Comment by oharboe** [comment]
@tgodzik  I downgraded to VSCode plugin 1.8.2, works fine. Thanks for the quick response!

**Comment by tgodzik** [comment]
@oharboe Published a new version, where I reverted one of the dependencies that seemed to have cause the issue. Could you check with the newest 1.8.4 ?

**Comment by oharboe** [comment]
@tgodzik  Works with 1.8.4. Thanks!

Since this is now fixed in the released version, I consider this issue closed.

**Comment by tgodzik** [comment]
I think this was an issue in the vscode language client dependency 6.1.2, they updated to 6.1.3, which most likely fixed the issue. Thanks for checking!
