### ISSUE TITLE
Failed to download Mentals on Fedora 30

### ISSUE THREAD

**Issue by irenepeggy** [scalameta/metals-vscode#253]
**Describe the bug**
When I launch my VS Code, I get this error message:

> Failed to download Metals, make sure you have an internet connection and the Java Home '/usr/local/java/jdk1.8.0_45' is valid. You can configure the Java Home in the settings.See https://scalameta.org/metals/docs/editors/vscode.html#http-proxy for instructions if you are using an HTTP proxy.

**Installation**

Operating system: Fedora 30 (Linux x64 5.0.9-301.fc30.x86_64)
VSCode version:  1.43.1
Metals server version:  0.8.3

**Additional context**

Running `echo $JAVA_HOME` gives `/usr/local/java/jdk1.8.0_45`
There is also no proxy settings on my computer

**Comment by tgodzik** [comment]
Hi thanks for reporting! We most likely need to release a fixed plugin version so that we can see why it didn't manage to download the server.

I will work on that tomorrow and I will let you know when you could retry.

**Comment by irenepeggy** [comment]
> Hi thanks for reporting! We most likely need to release a fixed plugin version so that we can see why it didn't manage to download the server.
> 
> I will work on that tomorrow and I will let you know when you could retry.

Thank you, looking forward for these fixes!

**Comment by tgodzik** [comment]
@tgodzik  Just released new plugin version, sorry for the wait! You should be able to restart Visual Studio Code if there are any real issues downloading Metals server it should show up in the bottom Output panel.

**Comment by irenepeggy** [comment]
@tgodzik Thank you! 
Finally, I have fixed the problem.
There was 
> Java Home '/usr/local/java/jdk1.8.0_45'

in the Mentals output, so I checked `/usr/local/java/` directory and found out that there was jdk1.8.0_231 instead of jdk1.8.0_45. So after I have set the correct $JAVA_HOME, everything works well.
