### ISSUE TITLE
it generates *always* .metals directory in VSCode

### ISSUE THREAD

**Issue by Raffaello** [scalameta/metals-vscode#299]
**Describe the bug**
it just always running even in non JVM / scala projects.

**To Reproduce**
install scala metals
and for example create a workspace that using go or python languages.

**Expected behavior**
to do not have .metals directory that is completely irrelevant for the project.

**Screenshots**

**Installation:**
- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code
- Metals version: v1.9.0

**Additional context**

**Search terms**

**Comment by olafurpg** [comment]
A workaround is to manually disable the Metals extension per-workspace, or go the other way around and manually enable the extension per-workspace

**Comment by Raffaello** [comment]
i noticed now: could be related to this repo the issue too:
https://github.com/scalameta/metals-vscode

**Comment by FranklinChen** [comment]
I just noticed this bug when opening a TypeScript project in VS Code and finding that Metals was launched and `.metals` created.

**Comment by tgodzik** [comment]
@FranklinChen did it happen with the newest version of the extension too? We reduced the number of patterns now, which should help out in situations where Metals is loaded due to timeout.

These are the current activasion events:
```
  "activationEvents": [
    "onCommand:metals.new-scala-project",
    "onDebugResolve:scala",
    "onLanguage:scala",
    "workspaceContains:build.sbt",
    "workspaceContains:build.sc",
    "workspaceContains:project/build.properties",
    "workspaceContains:src/main/scala",
    "workspaceContains:*/src/main/scala",
    "workspaceContains:*/*/src/main/scala"
  ],
```

If the change didn't help, we might need to remove the last 2 ones.

**Comment by FranklinChen** [comment]
It seems to be OK for me now.

**Comment by tgodzik** [comment]
Ok, I will close it for now, but if this ever happens again please report the issue here. Thanks!
