### ISSUE TITLE
Failed to download Metals

### ISSUE THREAD

**Issue by jast90** [scalameta/metals-vscode#315]
**Describe the bug**
```
Failed to download Metals, make sure you have an internet connection and the Java Home '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home' is valid. You can configure the Java Home in the settings.See https://scalameta.org/metals/docs/editors/vscode.html#http-proxy for instructions if you are using an HTTP proxy.
```
output of Metals
```
Java home: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
Error while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend/emoji_2.12/1.2.1/jars/emoji_2.12.jar: Ongoing concurrent download for https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend/emoji_2.12/1.2.1/jars/emoji_2.12.jar, ignoring it

```

**Installation:**

- Operating system: macOS
- VSCode version:Version: 1.45.1
- VSCode extension version:1.9.0
- Metals version: (found in VSCode settings, under `metals.serverVersion`)0.9.0

**Comment by tgodzik** [comment]
Thanks for reporting! There seemed to be a download problem, did you try reloading the window? It will retry the download.

In case you need to use proxies please take a look at https://scalameta.org/metals/docs/build-tools/proxy.html

**Comment by jast90** [comment]
Maybe a little complicated.

**Comment by tgodzik** [comment]
The proxy in most cases boils down to adding in Metals server options:
- `http.proxyHost=hostname` - the host name of the proxy
- `http.proxyPort=port_number` - the port number for the proxy

In case that you have only access to internal repositories, you should use coursier mirrors.

**Comment by tgodzik** [comment]
Did you manage to get it working with the proxies?

**Comment by jast90** [comment]
I don't have a proxy server.Whether there is a public proxy server，or how to build a？

**Comment by tgodzik** [comment]
You need a proxy usually if you are in a corporate network. You should be able to get some information from network administrators. They might also know what is the preferred way to download dependencies - some companies require to have them onboarded in a separate repository, in that case you would need a mirror.

**Comment by DavidFi1** [comment]
I have the same problem. :-(
I can download the problematic files with chrome without problem.
Is there a way to add the files manually? can I point to the files that are on my desktop some other way?

**Comment by tgodzik** [comment]
@DavidFi1  did you take a look at https://scalameta.org/metals/docs/troubleshooting/proxy? Did any of that help?

How are you normally able to download dependencies from Maven central?

**Comment by robsonpeixoto** [comment]
The same problema here, but using using VSCode on *macOS* using Remote SSH in a Ubuntu 20.04 VM. 
My remote settings  I configured:
```jsonc
  "metals.javaHome": "/usr/lib/jvm/java-11-openjdk-amd64",
```

But I got the error:
```
Failed to download Metals, make sure you have an internet connection and the Java Home '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home' is valid. You can configure the Java Home in the settings
```

**Comment by tgodzik** [comment]
@robsonpeixoto It's probably defined in the workspace settings which take precendence over Remote ones.

**Comment by robsonpeixoto** [comment]
Thanks @tgodzik . By mistake I committed the `.vscode` directory. Thanks

**Comment by eusme** [comment]
Metal makes me mad
