### ISSUE TITLE
All "command Metals.xxx-xxx not found"

### ISSUE THREAD

**Issue by zhaoxuyang13** [scalameta/metals-vscode#317]
**Describe the bug**

I'm using metals-vscode with a vscode remote SSH project. ( because I need a ubuntu environment)
I copy the "src/" directory and "pom.xml" to a new folder, and open it. ( the project is a Maven project)
then I install Scala(Metals) pluggin. ( which is exactly what i want )
then nothing happened  ( I assume i should get a "Importing a build" request from right-bottom.)

when I (command + shift + P) and  try every command of Metals, I get something like "command Metals.xxx-xxx not found".
I'm a little confused. and no one else seems to have this problem.

**To Reproduce** Steps to reproduce the behavior:

the steps are above. It's a clean server and Im working on scala project for the first time.

**Expected behavior**

**Screenshots**

It's a demo project indeed.
![image](https://user-images.githubusercontent.com/34227902/83621029-bc51c200-a5c0-11ea-8c3b-29c1d278770e.png)
![image](https://user-images.githubusercontent.com/34227902/83621035-beb41c00-a5c0-11ea-80f6-1530be9ff875.png)
![image](https://user-images.githubusercontent.com/34227902/83621041-bfe54900-a5c0-11ea-8f71-56046c0c20d9.png)

**Installation:**

- Operating system: Linux (ubuntu 18.04LTS)
- VSCode version: 1.39.1
- VSCode extension version: 1.84  ( but it pop out on bottom-right "Downloading V0.83")
- Metals version:  0.8.3

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! It looks like the server itself haven't managed to start, so the extension never got activated.
Is there maybe something in `.metals/metals.log`, Output (Metals) or Output(Extension Host) ?

**Comment by zhaoxuyang13** [comment]
Thanks for reply!
there is no .metals/ directory created.
and, may I ask what you mean by "Output(Metals), Output(Extension Host) ", I cannot figure out where to get the error log.
( I got my work done using pure maven, scala-maven-plugin and command line, not that convenient and interactive though)

**Comment by zhaoxuyang13** [comment]
ha.. I see the output.
"The language client requires VS Code version ^1.42.0 but received version 1.39.1"
Maybe I should update my VS Code version. Thanks.
