### ISSUE TITLE
Metals Extension Pane is Blank

### ISSUE THREAD

**Issue by Andreilys** [scalameta/metals-vscode#322]
Describe the bug
Hello, when I try to open the metals extension on VSCode I see a blank. My JAVA_HOME is set to a JDK that is version 11.

To Reproduce
Click metals extension

Expected behavior
Extension settings to not be blank

Screenshots
<img width="1882" alt="Screen Shot 2020-06-06 at 1 27 07 PM" src="https://user-images.githubusercontent.com/8299248/83953921-6d42a180-a7f9-11ea-8bdb-bfb90861d28e.png">

Installation:

Operating system: macOS
Editor: Visual Studio Code
Metals version: v1.9.0

**Comment by tgodzik** [comment]
Thanks for reporting! It looks like the extension is not activated. I will only activate if you are in a workspace with Scala code. If it's still not working inside one then there might be more information in in Output (Metals) or Output (Extension Host). We could try to figure out what's going on based on those logs.

**Comment by tgodzik** [comment]
Did you manage to get it working in a Scala workspace? In the future, we will also be adding a welcome view to create a new project in case of an empty workspace.

**Comment by tgodzik** [comment]
The welcome view should help out in this case. Closing this one as we don't actually have enough information.
