### ISSUE TITLE
Command "Reveal Active File in Side Bar" works only once

### ISSUE THREAD

**Issue by mgibowski** [scalameta/metals-vscode#332]
**Describe the bug**

**To Reproduce** 

1. Open any Scala file in vs code with metals extension enabled
2. Run command "Reveal Active File in Side Bar"
3. Close side bar (cmd + B)
4. Repeat running command "Reveal Active File in Side Bar"

**Expected behavior**

Having the side bar opened with metals focused on active file.

Currently nothing gets displayed, but it seems that this command triggers recompilation of the project.

**Installation:**

- Operating system: macOS
- VSCode version: 1.46.1
- VSCode extension version: 1.9.0
- Metals version: 0.9.0

**Comment by tgodzik** [comment]
Thanks for reporting! I can confirm the issue, if the class is revealed, it will not be focused later even if we run the command again.

Not sure if it's on the server or client side yet.
