### ISSUE TITLE
"New Scala Project" Button on VSCode doesn't do anything when pressed 

### ISSUE THREAD

**Issue by siddhant3s** [scalameta/metals-vscode#342]
The new "New Scala Project" that was added in the last Cobalt release doesn't do anything when clicked from a new VSCode Window.

It seems that the button only functions when we have already opened a directory. 

**To Reproduce** Steps to reproduce the behavior:

1. Open a brand new VSCode Window by going to File -> New Window
2. Go to the Metals tab on the left hand side bar
3. You should see a blue "New Scala Project" button under Packages pane.
4. Click on the button

Expected behavior: The "new project button" should start the new project flow or show an error explaining that the user needs to open a blank directory

**Screenshots**

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/295892/86388233-42593b00-bc49-11ea-92c0-b12561bc0a35.png">

**Installation:**

- Operating system: macOS/
- VSCode version:1.46.1
- VSCode extension version:1.9.1
- Metals version: 0.9.1

**Comment by kpbochenek** [comment]
Thanks for reporting!

Confirmed nothing is happening if no directory is opened.
