### ISSUE TITLE
unable to set metals version via User settings

### ISSUE THREAD

**Issue by kpbochenek** [scalameta/metals-vscode#374]
Change `workspace > Metals: Server Version` to nothing
Change `user > Metals: Server Version` to `0.9.2+70-55f2fdfe-SNAPSHOT` (taken from https://scalameta.org/metals/docs/editors/overview.html)
Reload VSCode window.

Expected in logs: `started: Metals version 0.9.2+70-55f2fdfe-SNAPSHOT in workspace`
Obtained in logs: `started: Metals version 0.9.2 in workspace`

When I set workspace settings it works correctly.

VSCode extension `v1.9.2` :)

**Comment by tgodzik** [comment]
I think that is VS Code specific and there is nothing we can do. If you have a workspace version specified it will override the user one. Best to check the json exactly, sometime I've seen even the default version specified in workspace settings, which I must have set at some point by mistake.

**Comment by kpbochenek** [comment]
To fetch `serverVersion` we use piece of code:

`config.get<string>("serverVersion")`

This will get first value that will be found: 'workspace setting' > 'global setting' > 'default value' nothing weird here.

We have in our configuration:
```
"metals.serverVersion": {
          "type": "string",
          "default": "0.9.2",
          "markdownDescription": "The version of the Metals server artifact. Requires reloading the window.\n\n**Change only if you know what you're doing**"
        },
```

That combination means that default value is exactly '0.9.2'.
This means:
- setting empty string as user/workspace metals version will mean change and will consider it as a specified value.
- setting '0.9.2' will consider it as **unspecified** value as it is equal to default.

As a result for user:
- setting X in UserConfig and '' in WorkspaceConfig will use Y :D (config will return '', on empty value we use default)
- setting X in UserConfig and '0.9.2' in WorkspaceConfig will use X :) (because 0.9.2 is default it is ignored)

Proposal:
Change default to be '', put in `makrdownDescription` information about default version. We already handle if config is empty -> use default version. No need for changes in code.

WDYT?

**Comment by tgodzik** [comment]
> Change default to be '', put in makrdownDescription information about default version. We already handle if config is empty -> use default version. No need for changes in cod

That default value is the only place we specify the version, so I don't think this will work.

**Comment by tgodzik** [comment]
Question is why is there an empty string in workspace?

**Comment by kpbochenek** [comment]
Ahh right `default` is defined in only one place. 

Is this default updated manually during release?

**Comment by tgodzik** [comment]
It is, it's in the release docs.

**Comment by kpbochenek** [comment]
Closing as it doesn't seem to be clear solution to this.
