### ISSUE TITLE
How to config vscode,  if I use maven build tools in metals-vscode?

### ISSUE THREAD

**Issue by yyHaker** [scalameta/metals-vscode#394]

**Comment by tgodzik** [comment]
Maven should work fine with Metals. An example of a Maven project can be found here https://github.com/scalameta/maven-scala-seed.g8

Once you open a root directory of the project you should get a pop up to import the project. Once it is finished you should be able to use all the features.

**Comment by yyHaker** [comment]
> Maven should work fine with Metals. An example of a Maven project can be found here https://github.com/scalameta/maven-scala-seed.g8
> 
> Once you open a root directory of the project you should get a pop up to import the project. Once it is finished you should be able to use all the features.

Thanks for give the good example, I means I have a project now, and it use Maven build tools, how do I configured the project in VSCode in order to use metals features? Should I create a build.sbt?

**Comment by tgodzik** [comment]
You need to open the directory with the `pom.xml` file. In the example I gave that would be the main directory in the repo itself.

**Comment by yyHaker** [comment]
> You need to open the directory with the `pom.xml` file. In the example I gave that would be the main directory in the repo itself.
Thanks for your good help, I can use all the features now! VSCode must open the directory with the pom.xml to use Maven build tools, otherwise it will not detect Maven.
