### ISSUE TITLE
Discoverability could be improved

### ISSUE THREAD

**Issue by ghisvail** [scalameta/metals-vscode#42]
`Metals` does not show up in the first results for a search on "scala" in the VSCode plugin manager.

One possible way of improving discoverability may be to change the name of the plugin to something like `Scala (metals)` (similar to `Scala (sbt)`), `Scala Language Server` or `Scala Language Server (metals)` (similar to Lulian Dragos' old plugin or the Dotty one).

**Comment by olafurpg** [comment]
What about "Metals Scala Language Server"? It's not a bad idea, the Marketplace search seems to favor extensions with "Scala" in the title (understandably).

**Comment by olafurpg** [comment]
Metals appears in the top row now for "Scala"

<img width="1239" alt="screenshot 2019-01-25 at 15 57 42" src="https://user-images.githubusercontent.com/1408093/51753428-0916b600-20ba-11e9-88c2-a2181cf26493.png">

Thanks for the suggestion @ghisvail

**Comment by ghisvail** [comment]
Awesome ! Thank you guys for your incredible work on Metals.
