### ISSUE TITLE
Unknown Symbol for Capitalized Variable Name When Assigned in Array

### ISSUE THREAD

**Issue by Xusine1131** [scalameta/metals-vscode#427]
**Describe the bug**

Hi, I'm told "not found: value S_XXX" when I'm trying to type this code in Scala:

```scala
val S_XXX :: Nil = (0 until 1).toList
```

Basically, I want to quickly initialize a sequence of variables with consistent value. Since these values are constant, I name them all upper cases but I met this error. If I just leave the first character lower case, everything is fine.

**To Reproduce** 

1. Write the same code as mine or whatever array assignment where one of the variables is in upper case.
2. Save and wait for the compiling & grammar checking.
3. See the error: not found: value S_XXXx bloop

**Expected behavior**

I don't think variable names in different cases could affect the grammar checking. 

**Screenshots**

![image](https://user-images.githubusercontent.com/8319391/96581292-e4289480-12d9-11eb-8901-ac0243565ec9.png)

**Installation:**

- Operating system: Linux
- VSCode version: 1.50.1
- VSCode extension version: 1.9.4
- Metals version: (found in VSCode settings, under `metals.serverVersion`) 0.9.4

**Additional context**

Maybe this is a bloop bug?

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! This is expected behavior and it also fails in sbt and repl.

In essence you are using pattern matching here and variables in pattern matches need to be lower case. Do you need to use pattern matching here? I would just do:

```scala
val S_XXX = (0 until 1).toList
```

there is no need to specify Nil at the end as it is always there in the list.

**Comment by Xusine1131** [comment]
@tgodzik Thank you for your explanation! So do you think this is a "trait" rather than a bug in Scala?

**Comment by tgodzik** [comment]
> @tgodzik Thank you for your explanation! So do you think this is a "trait" rather than a bug in Scala?

It's certainly not a bug. It's intended so that you can actually pattern match things like:
```scala
val S_XXX = 0
val S_XXX :: Nil = (0 until 1).toList
```
which will check that indeed the only element is 0. capitalized var names are for values coming from outside the pattern match itself.

**Comment by Xusine1131** [comment]
Thank you!
