### ISSUE TITLE
Inspecting Objects leads to "an implementation is missing"

### ISSUE THREAD

**Issue by rex-remind101** [scalameta/metals-vscode#435]
**To Reproduce** Steps to reproduce the behavior:

A. 
1. Run the debugger with a breakpoint.
2. Inspect any variable.
3. See "an implementation is missing".

B. 
1. Run the debugger with a breakpoint.
2. Enter `print("x")` in the console.
3. See "an implementation is missing".

**Expected behavior**

We should see variables, not "an implementation is missing".

**Screenshots**

<img width="1509" alt="Screen Shot 2020-10-30 at 7 09 15 PM" src="https://user-images.githubusercontent.com/4573957/97768861-6a678680-1ae3-11eb-90a9-5fe6b6e3a6c3.png">

**Installation:**

- Operating system: macOS 10.15.7
- VSCode version: 1.50.1
- VSCode extension version: v1.9.4
- Metals version: 0.9.4

**Search terms**

"an implementation is missing"

**Comment by tgodzik** [comment]
Thanks for reporting! We are still lacking `expression evaluator` in Metals, which is why you are seeing the errors. There is a feature request here: https://github.com/scalameta/metals-feature-requests/issues/83

**Comment by rex-remind101** [comment]
thanks! is there a timeline for when this might be available?

**Comment by tgodzik** [comment]
Unfortunately no, it's one of the harder topics and we do not have anyone who can work on it now.
