### ISSUE TITLE
Failed to connect with build server, no functionality will work

### ISSUE THREAD

**Issue by WegenPan** [scalameta/metals-vscode#440]
After I opened a maven project and clicked "import build",  it started download the jars and build, but failed with the log:

ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

can anyone tell me the reason? thxs

**Comment by tgodzik** [comment]
Thanks for reporting! Is there anything else in the logs?

Usually reloading the window might help, but if there is an underlying reason for the build server not working then it might not help.

What is your java version? Do you have java on PATH? What system are you using? Do you have a link to the project this is not working?

**Comment by WegenPan** [comment]
> Thanks for reporting! Is there anything else in the logs?
> 
> Usually reloading the window might help, but if there is an underlying reason for the build server not working then it might not help.
> 
> What is your java version? Do you have java on PATH? What system are you using? Do you have a link to the project this is not working?
> 
> Edit: Java is not needed on PATH, but the version available there might sometimes cause issues and will be picked up by the build server.

Thanks for your reply. I check the metals.log, and it shows:
**
> [0m[31m[E][0m Failed to load project from /xxx/.bloop/lookalike.json
> [0m[36m[T][0m bloop.data.Project$ProjectReadException: Failed to load project from  /xxx/.bloop/lookalike.json
> [0m[36m[T][0m 	bloop.data.Project$.fromBytesAndOrigin(Project.scala:216)
> [0m[36m[T][0m 	bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
> [0m[36m[T][0m 	bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
> [0m[36m[T][0m 	monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
> [0m[36m[T][0m 	monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
> [0m[36m[T][0m 	monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
> [0m[36m[T][0m 	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [0m[36m[T][0m 	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [0m[36m[T][0m 	java.lang.Thread.run(Thread.java:748)
> [0m[36m[T][0m Caused by: java.nio.file.AccessDeniedException: /data/home/wegenpan/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar
> [0m[36m[T][0m 	sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
> [0m[36m[T][0m 	sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
> [0m[36m[T][0m 	sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
> [0m[36m[T][0m 	sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
> [0m[36m[T][0m 	sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
> [0m[36m[T][0m 	sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
> [0m[36m[T][0m 	java.nio.file.Files.readAttributes(Files.java:1737)
> [0m[36m[T][0m 	bloop.ScalaInstance.$anonfun$hashCode$1(ScalaInstance.scala:79)
> [0m[36m[T][0m 	scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
> [0m[36m[T][0m 	scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
> [0m[36m[T][0m 	scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
> [0m[36m[T][0m 	scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
> [0m[36m[T][0m 	scala.collection.TraversableLike.map(TraversableLike.scala:273)
> [0m[36m[T][0m 	scala.collection.TraversableLike.map$(TraversableLike.scala:266)
> [0m[36m[T][0m 	scala.collection.AbstractTraversable.map(Traversable.scala:108)
> [0m[36m[T][0m 	bloop.ScalaInstance.<init>(ScalaInstance.scala:75)
> [0m[36m[T][0m 	bloop.ScalaInstance$.newInstance$1(ScalaInstance.scala:144)
> [0m[36m[T][0m 	bloop.ScalaInstance$.$anonfun$apply$7(ScalaInstance.scala:149)
> [0m[36m[T][0m 	java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
> [0m[36m[T][0m 	bloop.ScalaInstance$.apply(ScalaInstance.scala:149)
> [0m[36m[T][0m 	bloop.data.Project$.$anonfun$fromConfig$1(Project.scala:233)
> [0m[36m[T][0m 	scala.Option.flatMap(Option.scala:271)
> [0m[36m[T][0m 	bloop.data.Project$.fromConfig(Project.scala:228)
> [0m[36m[T][0m 	bloop.data.Project$.fromBytesAndOrigin(Project.scala:210)
> [0m[36m[T][0m 	bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
> [0m[36m[T][0m 	bloop.engine.BuildLoader$.$anonfun$loadBuildIncrementally$3(BuildLoader.scala:57)
> [0m[36m[T][0m 	monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
> [0m[36m[T][0m 	monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
> [0m[36m[T][0m 	monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
> [0m[36m[T][0m 	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [0m[36m[T][0m 	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [0m[36m[T][0m 	java.lang.Thread.run(Thread.java:748)
error: The launcher failed to establish a bsp connection, aborting...
2020.11.11 00:07:24 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)**

 I try to fix the error: "Caused by: java.nio.file.AccessDeniedException: /data/home/wegenpan/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar" , but failed. It's strange that the jar does exist in the path:
`-rwxrwxrwx 1 wegenpan users 5749423 11月 10 23:09 /data/home/wegenpan/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar`
And I chmod the path's premission to 777, but still no help.

**Comment by tgodzik** [comment]
That's weird :thinking: Are you using the WSL or SSH extension? My guess is that file is available on the remote machine, but not locally. Most likely it's a mismatch of where Metals is run and where the jars are available.

**Comment by tgodzik** [comment]
We haven;t managed to reproduce it, do let us know if this is still a problem, but closing for now.
