### ISSUE TITLE
Automatically pick up .jvmopts when launching server

### ISSUE THREAD

**Issue by antonoal** [scalameta/metals-vscode#45]
I'm trying to set up metals in VSCode on Windows machine that happens to use proxy to go to the internet.
When I start it I get the following error:
Error while downloading:
https://oss.sonatype.org/content/repositories/releases/io/get-coursier/coursier-cli_2.12/1.1.0-M9/coursier0cli_2.12-1.1.0-M9-standalone.jar:oss.sonatype.org, ignoring it
I've tried adding proxy info to .sbtops/.jvmops but that didn't seem to work.
Could you please help me to set it up?
Thanks, Alex

**Comment by antonoal** [comment]
Hi @olafurpg 
It does fix the problem. Thanks a lot!
Should I keep this issue open or close it?

**Comment by olafurpg** [comment]
@antonoal great! I've renamed the title to be about respecting .jvmopts when launching the server. To fix this issue, we should update the `serverProperties` array here https://github.com/scalameta/metals-vscode/blob/c88649324c73817d49a20a4c030181ec74fc4554/src/extension.ts#L83

to include the settings from `.jvmopts`.
