### ISSUE TITLE
Suggest adding variable type display function

### ISSUE THREAD

**Issue by dounine** [scalameta/metals-vscode#459]
## Function 1
like **Intellij IDEA** Press the shortcut key option+enter to display the suggested addition type display.
![image](https://user-images.githubusercontent.com/7344514/100849327-5e455f00-34bd-11eb-889d-f32b905d00b8.png)

## Function 2
Add configurable function of default display type
![image](https://user-images.githubusercontent.com/7344514/100850305-9a2cf400-34be-11eb-84aa-612e05645cd3.png)

**Comment by lubenxing** [comment]
You are such a handsome man

**Comment by ckipp01** [comment]
Thanks for the request @dounine. We actually have a separate feature-requests repo that contains this request. You can find two relevant requests here:

- https://github.com/scalameta/metals-feature-requests/issues/163
- https://github.com/scalameta/metals-feature-requests/issues/58
