### ISSUE TITLE
Pick the most recent Java 8 version

### ISSUE THREAD

**Issue by london-coder** [scalameta/metals-vscode#46]
Hi,
I tried to install Metals in VS Code on MacOS. Versions:
Metals 0.1.0
VS Code 1.25.1
MAC OS 10.14.2
locally installed Scala is 2.12.1

I followed the instructions on the website verbatim, and Metals does not work!

After installing Metals, I opened an existing sbt / scala project, opened several scala files and there was no "Import project" option anywhere. Furthermore, the metals.log file consisted of:
```
Jan 09, 2019 1:21:54 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.6.5.Final
Jan 09, 2019 1:21:54 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.6.5.Final
Jan 09, 2019 1:21:54 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 2.3.0.Beta2
INFO  Started Metals http server at http://127.0.0.1:5032
INFO  shutting down Metals
```

Which appears to offer no help in understanding why it does not work.
Is your project broken, or are the instructions wrong?
Regards,
Alan

**Comment by olafurpg** [comment]
I opened #47 to improve which Java 8 version is picked.
