### ISSUE TITLE
Pick the most recent Java 8 version

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals-vscode#47]
If the user has Java 8 `_11` and `_191` installed then we should pick `_191`. See #46 for related discussion. The relevant line to fix this issue is here https://github.com/scalameta/metals-vscode/blob/c88649324c73817d49a20a4c030181ec74fc4554/src/getJavaHome.ts#L20

**Comment by gabro** [comment]
Thanks for opening this. I can work on a fix later today
