### ISSUE TITLE
Error : "Failed to download Metals, make sure you have an internet connection and the java home is valid" and no log file created

### ISSUE THREAD

**Issue by JanausB** [scalameta/metals-vscode#503]
**Describe the bug**
Getting error message "Failed to download Metals, make sure you have an internet connection and the java home is valid" at startup. Metals output window lists Java home path and Metals version. No log file or .metals directory created anywhere on disk. No useful or relevant info in any other output windows.

**To Reproduce**:

1. Install the below listed versions of VS Code, the Sacla-lang extension, and metals extension from .vsix files
2. Create the "C:\Users\<userid>\AppData\Roaming\Coursier\config\mirror.properties" directory and create a mirror.properties file pointing to mirror repos
3. In VS Code, Configure metals "Custom repositories" to point to the mirror servers and configure Java Home to point to a valid Java bin directory
4. Reload VS Code and observe error message. Note that the metals server version is listed, implying that some stage to the initialization was successful. Additionally, no error metals.logs or .metals directory has been created

We have apache mirror repositories specified in both the mirror.properties file in Coursier/config and the custom repos in metals config. 

Despite running identical mirror and install files on several machines on the same network, the problem only occurs on one particular machine.  I have confirmed that the broken machine can pull deps down from the mirror repos using just sbt in a console and the projects still build, confirming the validity of the Java Home Path

**Expected behavior**

Metals to successfully download dependencies from the mirror server

**Installation:**

- Operating system: Windows 10 Pro, v20H2
- VSCode version: 1.53.0
- Scala-lang Version : 0.5.1
- VSCode extension version: 1.9.13
- Metals version: 0.9.10
- No additional extensions installed

**Comment by JanausB** [comment]
Troubleshooting Methods attempted:

- Deleting the local workspace and redownloading the repo
- Disabling antivirus and windows defender firewall 
- Windows defender allowances for associated executables
- Installing metals v1.9.12
- Uninstall\Reinstall of VS Code and Extensions
- Copy-Pasting files from functional setups to eliminate typo possibilities

**Comment by tgodzik** [comment]
Thanks for reporting! The only thing more that I can think of is that there is a typo in Java Home perhaps? Is there completely  nothing in Output (Metals)? I remember we hand an issue with some windows machines when using spaces or special characters in directories, but that should have been fixed. 

If there is exactly nothing different in case of this machine then the only way to debug it would be to try build the extension locally , but that would involve much more work.

**Comment by JanausB** [comment]
Thank you for your time sir.

So far there has been no instance of a metals.log file being created, nor a .metals directory being created in the scala directories we have loaded into VSC, which has made the troubleshooting process difficult. The projects still build from batch scripts and the Java home directory has been standardized across all machines currently successfully running metals, with the path copy-pasted from explorer to eliminate typos in both the environment variable and the metals java home setting, thus we do not suspect java_home as the culprit.

Looking at similar bug reports citing this particular error dialog, the fact that the output window lists both the java home directory and the metals version number (rather than a specific dependency that has failed to pull), mixed with the lack of logs suggests that instantiation has begun and that the process itself is crashing rather than simply erroring out, but combing thru windows event logs has rendered no meaningful results.

**Comment by tgodzik** [comment]
I will try to work on some better reporting on the VS Code plugin side, we might be able to get better information about it. I will try to take a look at it next week. If you need anything before that, compiling the extension is actually pretty easy, so you might be able to dig in that way. Let me know if you need any pointers.

**Comment by JanausB** [comment]
Root cause identified as an unrelated internal networking and configuration error and has been resolved. 

Thank you @tgodzik for your time sir.
