### ISSUE TITLE
Forwarded port for metals server kept open

### ISSUE THREAD

**Issue by TurboGofre** [scalameta/metals-vscode#533]
**Describe the bug**

There is an issue with auto forwarded port for metals server. Each time I connect to my remote container (scala-sbt), a new port is auto forwarded but kept for next sessions. However, I end up with dozens of forwarded ports and I have to close each manually.

**To Reproduce** Steps to reproduce the behavior:

1. Open a scala project on a remote host
2. Port is open as "Auto forwarded" for Metals server (see screenshot 1)
3. Close vscode instance and reconnect to remote (or use the reload window command)
4. New port is forwarded but old one is forwarded too (see screenshot 2)

**Expected behavior**

Vscode should not keep the old port forwarded as Metals seams to use a random port each time

**Screenshots**
![screenshot1](https://user-images.githubusercontent.com/19334022/113882548-ae129a80-97bd-11eb-87f8-37c051d83ed1.png)
![screenshot2](https://user-images.githubusercontent.com/19334022/113883405-6b04f700-97be-11eb-92df-431672d2cd3b.png)

**Installation:**

- Operating system: macOS/Windows/Linux
- VSCode version: 1.55.0
- VSCode extension version:
- Metals version: 0.10.1

**Additional context**

Used in a docker container with remote-container extension

**Search terms**

metals server port forwarding remote container docker open

**Comment by tgodzik** [comment]
Thanks for reporting! I am not sure we would be able to fix it on our side. The only thing we are doing is creating the language client here:

https://github.com/scalameta/metals-vscode/blob/7b921175a07dd7c9d88ef16e116c4e96ded74fda/src/extension.ts#L334

I might be wrong, I have no idea how remote contaienrs work, but honestly I don't see exactly what we would be doing wrong.

**Comment by TurboGofre** [comment]
Investigation progress here : https://github.com/microsoft/vscode-remote-release/issues/4843

**Comment by tgodzik** [comment]
It seems that the corresponding issue was closed.
