### ISSUE TITLE
Failed to download Metals Server Version 0.10.1

### ISSUE THREAD

**Issue by AhmedMesawer** [scalameta/metals-vscode#534]
**Describe the bug**

since latest version 0.10.1 and this error appears to me 
![image](https://user-images.githubusercontent.com/35766435/113895140-f5525880-97c8-11eb-91d8-20ac741c4b01.png)

**Comment by AhmedMesawer** [comment]
using older versions doesn't solve the problem for me

**Comment by tgodzik** [comment]
That's weird, I might release a new version of the extension with the updated coursier, that should have this fixed.

**Comment by keithnull** [comment]
Same issue here :(

**Comment by tgodzik** [comment]
I will run a release then with the updated coursier.

**Comment by tgodzik** [comment]
@keithnull @AhmedMesawer could you check if it works with the newest version of the extension? 1.10.2 ?

**Comment by keithnull** [comment]
@tgodzik  Thanks for your fix, `1.10.2` works perfectly for me🎉

**Comment by AhmedMesawer** [comment]
@tgodzik me too
