### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ashwinbhaskar** [scalameta/metals-vscode#538]
- Issue Type: `Bug`
- Extension Name: `metals`
- Extension Version: `1.10.1`
- OS Version: `Linux x64 5.8.0-48-generic`
- VS Code version: `1.55.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 173,
		"activateCallTime": 3,
		"activateResolvedTime": 741,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "scalameta.metals",
				"_lower": "scalameta.metals"
			},
			"activationEvent": "onLanguage:scala"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Coursier exit: 255"
		}
	]
}
```

**Comment by tgodzik** [comment]
Thanks for reporting, do you have any more information in `Output (Metals)` ?

**Comment by tgodzik** [comment]
Let us know if you are able to provide any more info, it seems coursier failed to download Metals server, but aside from that we should see more info in the output.
