### ISSUE TITLE
Frequent UI stalls when typing in Scala files

### ISSUE THREAD

**Issue by matthughes** [scalameta/metals-vscode#548]
**Describe the bug**

VsCode with Metals installed frequently stalls when I'm typing for several seconds.  Seconds later, the enqueued keystrokes appear.  I've disabled every extension besides VIM, Metals, Scala Syntax.

I've tried profiling the extension several times but can never find a blocking call in the extension host.  It appears to be in VsCode but only happens when Metals is installed.

I filed a bug with VsCode here: https://github.com/microsoft/vscode/issues/122196 but thought I'd cross-post because some combination of Metals/VsCode seems to be the culprit.

**Expected behavior**

Metals/VsCode should never delay keystrokes.  If IDE can't keep up with keystrokes, it should delay all processing until some quiet period.  That is, each keystroke should cancel any outstanding requests to LSP (if indeed that's what's causing this problem).

**Installation:**

- Operating system: macOS BigSur
- VSCode version: 1.55.2
- VSCode extension version: 1.10.4
- Metals version: (found in VSCode settings, under `metals.serverVersion`)

I have the "Show Implicit / Inferred Types / Super Method Lenses" all turned off.

**Comment by matthughes** [comment]
It's possible this is an issue with the latest (0.5.3) release of https://github.com/scala/vscode-scala-syntax.  I downgraded to 0.5.2 and so far haven't seen anything near as bad.  That I'm not seeing any stalls in the extension profiling seems make this more likely.

**Comment by tgodzik** [comment]
Thanks for reporting! We might need to fix it in scala-syntax then. I will experiment also a bit to see if I will encounter this issue also.

**Comment by matthughes** [comment]
Sorry to report but looks like the stalls are back even after going to 0.5.3.  Gonna try and drop down to older Metals release to see if that helps.

**Comment by tgodzik** [comment]
> Sorry to report but looks like the stalls are back even after going to 0.5.3. Gonna try and drop down to older Metals release to see if that helps.

Did you mean `0.5.2` ?

**Comment by matthughes** [comment]
Yes sorry.  I downgraded to 0.5.2 still seeing the stalls (stall = Process Explorer reporting 100% CPU on window and delays of key presses by more than 2 seconds).  Tried downgrading Metals to 1.10.0 still seeing it.  Tried downgrading Vim to 0.19.3 and still seeing it.  I can take more profiles of VsCode but honestly they look identical to the one I already attached.

Gonna try to run the Insiders version and see if that makes anything better.

**Comment by tgodzik** [comment]
If downgrading doesn't help and this only popped up recently, might it have something to do with your system? Or maybe a particular project brought in the issues or is it everywhere?

**Comment by matthughes** [comment]
I disabled Metals (still have VIM/Scala syntax) and the editor is working
perfectly now.  Granted I've lost enormous functionality but at least it
can keep up with my typing.  I've seen behavior like this for a long time.
Sometimes I'd restart VsCode and things would return to normal and I'd
forget about it and move on.  Feel like I'm going crazy cause no one else
seems to be having this problem but I certainly can't be the only user to
have VIM/Metals installed.

Would it be helpful to take both an extension profile (with metals enabled)
and the CPU profile at the same time, assuming that's possible?

**Comment by tgodzik** [comment]
I haven't worked much with CPU profiles, so I would need to dig in here. I haven't seen the issue anywhere also, but was that not an issue with ` Bracket Pair Colorizer 2 ` at some point? I remember you wrote about it on gitter recently.

Maybe this is an issue with the LSP Client in Vs Code somehow? Metals doesn't really do too much inside VS Code extension itself.

**Comment by matthughes** [comment]
When I started debugging this, I did see an issue with Bracket Pair
Colorizer, but removed that last week.  Past couple days have
only Metals/Scala Syntax/VIM installed.

I took the nuclear option and blew away my workspace,
~/Library/Cache/com.microsoft.* and started with a brand new install with
just Vim and Metals and everything has been snappy so far.

When I do extension profile, I don't see

**Comment by tgodzik** [comment]
WWe haven't managed to find a reproduction here, so closing for now. If this happens again we can reopen.
