### ISSUE TITLE
Import autocomplete broken in v1.10.4

### ISSUE THREAD

**Issue by spangaer** [scalameta/metals-vscode#549]
**Describe the bug**

When auto completing, leading to an import statement being generated, the FQN gets inserted at place of edit with a random other type in front of it (See gif). In the example it shows Token, but before that it was LOpType. Both are custom types in my code base.

**Expected behavior**

Add an import statement (still works correctly in v1.10.3)

**Screenshots**

![Animation](https://user-images.githubusercontent.com/677147/116101969-92a8fa00-a6ae-11eb-9746-256b8646d3d9.gif)

**Installation:**

- Operating system: Windows
- VSCode version: 1.55.2
- VSCode extension version: 1.10.4
- Metals version: 0.10.2

**Comment by tgodzik** [comment]
Thanks for reporting! This was unearthed when fixing one other bug and should be fixed in the next release.

Already reported https://github.com/scalameta/metals/issues/2736 and we have a fix ready.

You can downgrade Metals server version to 0.10.1 to avoid this issue until 0.10.3 release.
