### ISSUE TITLE
No suggestion when typing

### ISSUE THREAD

**Issue by futurehome** [scalameta/metals-vscode#574]
Issue Type: <b>Bug</b>

Hi, 

When I compile a scala file, there is no suggestion popup. Any other setting  needed to enable the suggestions?

Thanks,
Alex

Extension version: 1.10.5
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (0.45GB free)|
|Process Argv|--crash-reporter-id e8f83c50-8383-48da-9b44-a0190dc5a0ac|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30302759
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by tgodzik** [comment]
thanks for reporting! Did you mean completions? They should work after you import the project, which should pop up after opening a project with Scala files in them. 

You can find more docs here: https://scalameta.org/metals/docs/editors/vscode.html

**Comment by futurehome** [comment]
Yes, after importing, I can jump between files by pressing ctrl and mouse left together, but I still can't get the completion.


And it always shows “loading" like pic below when I hover the mouse over the keyword, but without any result.
![image](https://user-images.githubusercontent.com/6230304/119657270-447a4880-be5e-11eb-8a10-ee16081f3cd9.png)

**Comment by tgodzik** [comment]
That's weird, do you get something in the Metals logs? `.metals/metals.log` should contain the full logs including any issues that might be encountered in the compiler, which is where the completions are coming from.

**Comment by futurehome** [comment]
attached is log file, looks like there are a lot of about completion.
[metals.zip](https://github.com/scalameta/metals-vscode/files/6546718/metals.zip)

**Comment by tgodzik** [comment]
That seems to happen when using Scala 2.11.12 and newer JDK versions. Related https://github.com/scalacenter/bloop/issues/743

What is the Scala version you are using and the JDK version?

**Comment by futurehome** [comment]
![image](https://user-images.githubusercontent.com/6230304/119667585-00d90c00-be69-11eb-927f-373e3cb6e1f9.png)

**Comment by futurehome** [comment]
You're right, but how to refresh it? I have only 2.12.13 installed on my computer.
![image](https://user-images.githubusercontent.com/6230304/119670010-1ea77080-be6b-11eb-8ea4-e22b35a3b888.png)

**Comment by tgodzik** [comment]
The version is coming from the build definition. The only way to change it is to change it in `build.sbt`. The scala binary installed on the PATH is never actually used by any of the tools. The usually have their own deinfition. Alternatively, you could install JDK 8, which would make the current build definition work.

Some more info on sbt https://www.scala-sbt.org/1.x/docs/Basic-Def.html

**Comment by futurehome** [comment]
Yes, after installing JDK 8, everything looks good. Thanks for the quick response and support.

Alex

**Comment by tgodzik** [comment]
Glad to be of help!

The `scala` executable is a bit misleading for people for sure, it's something we are aware of and are working on making better.

Next time you could also ask on Discord, the answer would be faster than via issues.
