### ISSUE TITLE
Stuck at "Starting Metals server ..."

### ISSUE THREAD

**Issue by futurehome** [scalameta/metals-vscode#576]
After I launch the vscode, the metal server should start automatically, the vscode shows “Starting metal server ...." at the left lower corner, but there is no content in Metal Build Command, and I can do nothing further. 
But if I restart my computer, it can launch metal server successfully when I lauch vscode at first time. And it will fail if I quit and launch vscode again. 

Thanks,
Alex

![image](https://user-images.githubusercontent.com/6230304/120058428-61409700-c07d-11eb-89a1-9c1fac388bde.png)

Issue Type: <b>Bug</b>

Frmo the output tab, it looks like ok, 

Java home: C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot
Metals version: 0.10.3
2021.05.29 12:46:08 INFO  logging to file C:\prj\SpinalWorkshop-workshop\SpinalWorkshop-workshop\.metals\metals.log
2021.05.29 12:46:08 INFO  Started: Metals version 0.10.3 in workspace 'C:\prj\SpinalWorkshop-workshop\SpinalWorkshop-workshop' for client Visual Studio Code 1.56.2.
2021.05.29 12:46:08 INFO  Flyway Community Edition 7.9.0 by Redgate

Extension version: 1.10.5
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.18GB free)|
|Process Argv|--crash-reporter-id e8f83c50-8383-48da-9b44-a0190dc5a0ac|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by futurehome** [comment]
But it can only work at first launch after I restart my computer.

![image](https://user-images.githubusercontent.com/6230304/120058531-15422200-c07e-11eb-9f76-8f1a86b813aa.png)

**Comment by tgodzik** [comment]
Thanks for reporting! Are you getting anything in `.metals/metals.log` file? Does it happen in all your projects? Did you try to remove `.metals` directory and restarting?

**Comment by futurehome** [comment]
It looks ok after I removed .metals, thanks for the help.

Alex
