### ISSUE TITLE
Extension is wrongly disabled

### ISSUE THREAD

**Issue by stefanrybacki** [scalameta/metals-vscode#595]
**Describe the bug**

Metals extensions says it is disabled because it depends on an extension that is disabled.
However the only dependency listed is "Scala Syntax (official)" which is enabled (see screenshot)

**To Reproduce** Steps to reproduce the behavior:

Latest Insider Build of vscode (see current version in screenshots)

Install metals extension

**Expected behavior**

The metals extension is enabled.

**Screenshots**

![image](https://user-images.githubusercontent.com/29799350/123096003-f0e42600-d42e-11eb-924b-e8a7ff1c2982.png)
![image](https://user-images.githubusercontent.com/29799350/123096109-0b1e0400-d42f-11eb-978c-5ebcd3991a1a.png)

**Installation:**

- Operating system: Windows with Workspace on WSL (Ubuntu)
- VSCode version: see screenshot
- VSCode extension version: v1.10.6
- Metals version: (found in VSCode settings, under `metals.serverVersion`) since extension is disabled settings does not exist

**Comment by dos65** [comment]
@stefanrybacki 
Thanks for reporting but it looks more like an issue with this Insiders build.

**Comment by tgodzik** [comment]
I does seem like an issue with the insiders build, I managed to reproduce. To workaround it I manually disabled Scala syntax and then enabled both syntax and Metals, which seems to have worked. Best to report it in VS Code itself, I can't find anything in the logs itself that points to Metals.

**Comment by stefanrybacki** [comment]
@tgodzik @dos65 yes I was afraid it might be related to vscode itself, thanks for checking.

**Comment by stefanrybacki** [comment]
@tgodzik @dos65 it now happens also to the official visual code version. Please check.

Version: 1.58.0 (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by tgodzik** [comment]
We merged a fix to scala syntax, as soon as it is released it should work. More info https://github.com/scalameta/metals-vscode/issues/613
