### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bballamudi** [scalameta/metals-vscode#601]
- Issue Type: `Performance`
- Extension Name: `metals`
- Extension Version: `1.10.6`
- OS Version: `Linux x64 5.4.0-77-generic`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/scalameta.metals-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by tgodzik** [comment]
Thanks for reporting! The extension itself doesn't do anything heavy, so this should not be an issue. We are also lacking any kind of information to debug it. 

```
Make sure to attach this file from your home-directory:
/tmp/scalameta.metals-unresponsive.cpuprofile.txt
```

If this happens again please do attach the cpuprofile.
