### ISSUE TITLE
Scala (Metals) extension is disabled in visual code-insiders 

### ISSUE THREAD

**Issue by hwait** [scalameta/metals-vscode#605]
Scala (Metals) extension is disabled in Visual Studio Code Insiders.

Scala (Metals) extension shown grayed out in WSL: UBUNTU-20.04 - INSTALLED group of extensions. 
There is the notification "The extension has been disabled because it depends on an extension that is disabled." shown in the header.

**To Reproduce** Steps to reproduce the behavior:

1. Add Scala (Metals) extension in your code-insiders 
2. See it disabled

**Expected behavior**

Scala (Metals) extension enabled and works well

**Screenshots**

![image](https://user-images.githubusercontent.com/5249957/124249897-2206d980-db46-11eb-9526-87225d91e94c.png)
![image](https://user-images.githubusercontent.com/5249957/124249956-321eb900-db46-11eb-88df-00d20b521c1c.png)
![image](https://user-images.githubusercontent.com/5249957/124252208-89be2400-db48-11eb-8ac5-54fd63bf0674.png)

**Installation:**

- Operating system: Windows Insiders
- VSCode version: 1.58.0-insider (user setup)
- VSCode extension version: Scala syntax (official) version is 0.5.3
- Metals version: v1.10.6 (there is no any `metals.*` in VSCode settings )

**Additional context**

The extension `Scala syntax (official)` is located in LOCAL - INSTALLED group of extensions. 
There is the notification "This extension is enabled globally" shown in the header.
This extension also shown in WSL: UBUNTU-20.04 - INSTALLED group of extensions, but it is grayed out. 

**Search terms**
Scala (Metals) code-insiders

**Comment by tgodzik** [comment]
Thanks for reporting! This seems to be a bug in VS Code itself. I think last time I checked if you disabled both extensions and enabled them again it started to work again.

There is nothing we actually do in Metals aside from:
```
  "extensionDependencies": [
    "scala-lang.scala"
  ]
```
so there is not much we can do unless anything changed recently. Could you report it in the VS Code repository?

**Comment by hwait** [comment]
Unfortunately disable/enable, reinstall extensions didn't help. Thank you for your immediate response, I'll create an issue in VS Code repository itself a bit later.
