### ISSUE TITLE
Metals doesn't work with Docker container or WSL2 remote in latest VSCode

### ISSUE THREAD

**Issue by dboreham** [scalameta/metals-vscode#613]
This problem seems to have crept in with a recent VSCode insiders release (last week or two). The problem is not present in the regular non-insiders VSCode.

Reproduce:

1. Create an empty directory in WSL2.
1. Open a new VSCode window.
1. Select "Open folder in WSL2".
1. Pick the empty directory.
1. Click to trust the folder.
1. Install the "Scala Metals" VSCode extension.
1. Observe that the extension is disabled for mysterious reasons.

Comparing the flow with regular non-insiders VSCode, I noticed that there is a popup displayed saying that the scala-lang extension is required and prompting to approve downloading. Prior to approval things seem to be in the same state as observed with insiders VSCode. So it could be that something is going wrong to do with the dependency installation. I don't see that same popup with insiders VSCode.

Result looks like:

![image](https://user-images.githubusercontent.com/1649760/124953277-3b8aa400-dfd2-11eb-9078-16c4a820245f.png)

Note also that everything works as expected in the "local" (Windows) installation for metals. The problem only appears with WSL2 remote, I think it also happens with Docker containers but haven't re-tested that scenario recently.

VSCode devs over here: https://github.com/microsoft/vscode/issues/127067 verified that this doesn't seem to be related to the recently introduced folder trust feature in VSCode insiders (as originally suspected).

```
Version: 1.58.0-insider (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-07T12:09:55.219Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000
```

Scalameta : v1.10.6

Scala-lang: v0.5.3

**Comment by tgodzik** [comment]
Thanks for reporting! This was already reported in https://github.com/scalameta/metals-vscode/issues/605, however Metals relies completely to install the Scala Syntax extension. The only thing we set is the dependency:

https://github.com/scalameta/metals-vscode/blob/main/package.json#L621

I don't believe there is anything we can do in Metals, especially that seems to work in non-insiders VS Code.

**Comment by dboreham** [comment]
> Thanks for reporting! This was already reported in #605, however Metals relies completely on VS Code to install the Scala Syntax extension. The only thing we set is the dependency:
> 
> https://github.com/scalameta/metals-vscode/blob/main/package.json#L621
> 
> I don't believe there is anything we can do in Metals, especially that seems to work in non-insiders VS Code.

Thanks. I did look for an existing dup before filing this, but since the dup had been closed, it didn't appear in the bug list :(

I'll go back to VSCode devs..

**Comment by dboreham** [comment]
btw after today's update, it doesn't work with the regular (non-insiders) VSCode either.

**Comment by tgodzik** [comment]
Opened and issue here: https://github.com/microsoft/vscode/issues/128375

**Comment by kammoh** [comment]
I guess changing the issue's title would be in order as it currently affect the latest vscode release (not just the insider version) and also regular SSH remote sessions, e.g. Linux machone, and not just WSL2 or docker.

**Comment by kammoh** [comment]
I locally building `scala-lang.scala` main branch (following steps similar to CI:deploy with a bumped version) and installed it on the host and then the remote, but metals still does not load.

**Comment by tgodzik** [comment]
Best to revert to an earlier version of VS Code for the time being, but that should have fixed it.

There is also a possibility that VS Code team will fix it in their codebase, they've been quite responsive on this.

**Comment by ye-will** [comment]
Found a workaround. Just put these lines in your local `settings.json`.

```
{
    "remote.extensionKind": {
        "scala-lang.scala": [
            "workspace"
        ]
    }
}
```

Read more: https://code.visualstudio.com/docs/remote/ssh#_advanced-forcing-an-extension-to-run-locally-remotely

**Comment by kammoh** [comment]
> Found a workaround. Just put these lines in your local `settings.json`.
> 
> ```
> {
>     "remote.extensionKind": {
>         "scala-lang.scala": [
>             "workspace"
>         ]
>     }
> }
> ```
> 
> Read more: https://code.visualstudio.com/docs/remote/ssh#_advanced-forcing-an-extension-to-run-locally-remotely
This workaround solved the issue for me👏👏👏 Thank you @ye-will!

**Comment by tgodzik** [comment]
New scala-syntax extension was released and looks to be working on Windows with WSL 2. Closing for now, let me know if more issues pop up.
