### ISSUE TITLE
Cannot enable Metal despite the Scala Syntax (Official) is enabled globally 

### ISSUE THREAD

**Issue by korntewin** [scalameta/metals-vscode#616]
**Describe the bug**
Cannot enable Metal from the dependency problem despite the Scala Syntax (Official) is enabled globally. But, the metal can still be enabled if it is installed outside of WSL.

**To Reproduce** Steps to reproduce the behavior:

1. Install VScode's Scala (Metals) extensions in WSL: Ubuntu-20.04 

**Expected behavior**

1. Can enable metal in VSCode WSL

**Screenshots**

![image](https://user-images.githubusercontent.com/31014250/125154967-096e7300-e187-11eb-9e9d-576ac97361a6.png)
![image](https://user-images.githubusercontent.com/31014250/125154989-2d31b900-e187-11eb-80a9-3bde13f4a45a.png)

**Installation:**

- Operating system: macOS/Windows/Linux
- VSCode version: 1.58.0
- VSCode extension version: 1.10.6
- Metals version:  0.10.4

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! This seems an issue within VS Code, the behaviour changed recently and now extensions are disabled if their dependencies are not enabled, which seems to be confused when there is a UI extension and a remote one dependending on it.

Current workaround is https://github.com/microsoft/vscode/issues/127067#issuecomment-877289829

>Adding the remote extension behavior in my settings.json fixed the issue for me
> "remote.extensionKind": { "scala-lang.scala": [ "workspace" ] }

Closing in favour of https://github.com/scalameta/metals-vscode/issues/613

**Comment by korntewin** [comment]
Thanks!

**Comment by tgodzik** [comment]
I raised an issue just in case: https://github.com/microsoft/vscode/issues/128375

If we don't get any response from the VS Code team we'll make the workaround change to the scala-syntax extension.

**Comment by korntewin** [comment]
> 
> 
> I raised an issue just in case: [microsoft/vscode#128375](https://github.com/microsoft/vscode/issues/128375)
> 
> If we don't get any response from the VS Code team we'll make the workaround change to the scala-syntax extension.

You may not know this, but I am truly appreciate for what you, microsoft team and scala lang team have done on the small defect of mine.  Right now, I can use metal on WSL2 by removing the extension kinds as you do. But I can't wait for the next scala-lang version!
