### ISSUE TITLE
Extension no longer loads in VSCode 1.58 using SSH Host

### ISSUE THREAD

**Issue by aishfenton** [scalameta/metals-vscode#617]
**Describe the bug**

When loading my workspace, using an SSH remote host, the Metals extension is disabled and has no option to re-enable it. It says (on at Metals extension screen) `this extension is disabled because it depends on an extensions that is disabled`. 

* Looking at the dependent extensions, there is only one listed: the official Scala syntax, and that says it's enabled (and indeed does seem to be working fine).

* Disabled/Re-enabling or Reinstalling the Metals extension makes no difference. It always comes up disabled.

* Loading a local Scala project (i.e. not over SSH) the extension is enabled and works as previously.

* Reverting to VScode 1.57.1 everything works as fine again (i.e. the extension is still enabled when using an SSH host) 

**To Reproduce** Steps to reproduce the behavior:

1. Connect to a Scala project over SSH
2. Go to the Metals extension screen.
3. See that it's disabled, with no option for re-enabling it (and has above note, about dependent extension being disabled).

**Installation:**

- OS: macOS 11.4
- VSCode version: 1.58
- VSCode extension version: 1.10.6
- Metals version: 0.10.4

**Search terms**

SSH, Extension Disabled

**Comment by tgodzik** [comment]
Thanks for reporting! This is related to recent change to VS Code, which will now disable a workspace extension if it depends on a UI one. We made a change to scala-lang that should help out here:
https://github.com/scala/vscode-scala-syntax/pull/210

**Comment by tgodzik** [comment]
Also closing in favour of https://github.com/scalameta/metals-vscode/issues/613
