### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Boitumelo2010** [scalameta/metals-vscode#620]
- Issue Type: `Bug`
- Extension Name: `metals`
- Extension Version: `1.10.6`
- OS Version: `Linux x64 5.4.0-4parrot1-amd64`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by tgodzik** [comment]
Thanks for reporting, but we need to have some more information about what is an issue. Please let us know what is the problem you encountered, so that we can act based on that information.

**Comment by Boitumelo2010** [comment]
Scala(metals) is unresponsive in my visual studio code,i can't even type

**Comment by tgodzik** [comment]
Is it only the editor or globally everything seems slugish? Is there anything in the logs? You can take a look at `Output` and search through different outputs for something out of the ordinary.

The only possibility I see is that `-Xmx` is not set and Metals is taking up memory, so we are running out of it. You could try doing `killall java` to see if the editor starts being responsive. You can set max memory in the server settings and also it might be needed to set it for Bloop, which is a build server used underneath. https://scalacenter.github.io/bloop/docs/server-reference#custom-java-options
