### ISSUE TITLE
Scala Intellisense stops working if there is a `match` statement in the code somewhere below the line being entered

### ISSUE THREAD

**Issue by Wonderer0** [scalameta/metals-vscode#653]
**Describe the bug**

Scala Intellisense hints/suggestions stops working if there is a `match` statement in the code somewhere below the line being entered, unless immediately followed by a `val` or `var` declaration.  This can be shown by the following experiment.

**To Reproduce**

Type in the code below in 4 stages, after each stage try typing `msg.` to see if Intellisense is still working, then delete `msg.` before typing in the next code:

1. When there isn't a `match` statement below `msg.` Intellisense hints as soon as the `.` is entered.

1. After the `match` statement is added Intellisense doesn't give any hints (but does show the correct type info).

1. Adding a `val` or `var` between `msg.`and the `match` makes Intellisense work OK again.

1. Adding another statement between `msg.` and the `val` stops it from working again.

```
@main def hello: Unit = {
  val msg = "Hello world!"
  val opt: Option[String] = Some("thing") 
  // (1) Intellisense works when nothing below msg.
  
  msg.
  
  println("It stops again") // (4) Adding this line stops it again.
  val x = "It works again"  // (3) Adding this line makes it work again

  opt match {               // (2) Adding match stops Intellisense
    case Some(value) => println(opt)
    case None        =>
  }
}
```
**Expected behavior**

That Intellisense suggestions would not be affected by a match statement anywhere below it.

**Installation:**

- Operating system: Windows 10 (x64), Version: 21H1, Build: 19043.1165.
- VSCode version: Discovered in1.59.1.  Confirmed in 1.60.0-insider.
- Metals version: 1.10.8 (found at top of Metals page in VSCode)
- `metals.serverVersion`: 0.10.5 (found in Feature Contributions in Metals page)
- Scala Syntax (official:): 0.5.4
- Language Support for Java(TM) by Red Hat: 0.81.0
- Scala 3.0.1, installed by Coursier

**Additional context**

`bloop.settings.json` has:  `"semanticDBVersion": "4.4.24"` and the highest `supportedScalaVersions` is `2.13.6`.  I tried adding `3.0.1` and running 'Import build', but this didn't have any effect.

The project was created in VSCode 1.59.1 as a "scala/scala3.g8" project by Metals, but re-tested using the insider version.

Intellisense hinting is a lot less reliable for Scala than JS.  Sometimes it stops working completely for no apparent reason, and sometimes only gives hints after a few characters have been entered after the `.`.  However this problem does seem to be a reproducible bug, which might perhaps throw light on other problems.

I am a newbie to Scala and Java, and their build environments, so would appreciate any help if this isn't a bug but something in my setup.

**Search terms**

Intellisense, code completion, content assist, code hinting, match statement

**Comment by tgodzik** [comment]
Thanks for reporting! I think this should be raised in Metals, but could you try the newest SNAPSHOT version? I think we fixed i there:

https://scalameta.org/metals/docs/#latest-metals-server-versions

**Comment by Wonderer0** [comment]
I too am now confused about which repo I should be reporting this bug to, and where to download the latest SNAPSHOT from.  :confused: Your link goes to scalameta.org/metals, and its GitHub home is scalameta/**metals**, not scalameta/**metals-vscode** (where we are now) which I assume is for builds of Metals for VSCode.  Do I need to download the latest Metals source from scalameta/metals and incorporate it into the scalameta/metals-vscode source code somehow and then build a VSIX file from that? 

According to `CONTRIBUTING.md` building it requires `yarn`, which is installed using `npm`, so would I have to also install `node`?  This all seems like a lot of work to get the latest SNAPSHOT, so unless you can point me to a VSIX of it I shall wait until the next official release of Metals for VSCode.

In the meantime could you check whether or not it is fixed in the latest SNAPSHOT release please, perhaps using my experiment above.

**Comment by Wonderer0** [comment]
Thanks for explaining the relationship between Metals-VSCode and the Metals server.  Understanding that I now see that the necessary information was already there in the VSCode page of the Metals site.

Yes, that SNAPSHOT version has fixed the bug thanks.

Should any similar bugs in the future be reported straight to scalameta/metals rather than here, even though the Repository link from the extension in VSCode comes to here?

**Comment by tgodzik** [comment]
Thanks for checking it out!

> Should any similar bugs in the future be reported straight to scalameta/metals rather than here, even though the Repository link from the extension in VSCode comes to here?

I think so, since most of the logic is contained in the server itself. But we always can transfer it ourselves, so this is not a big deal if open it here. We can then confirm it's indeed an issue in the server.
