### ISSUE TITLE
Metals ignores JAVA_HOME because locate-java-home npm…

### ISSUE THREAD

**Issue by hedefalk** [scalameta/metals-vscode#657]
metals-vscode doesn't honor JAVA_HOME because it uses locate-java-home npm packages that doesn't. There's a PR to fix that but it seems to be a dead project?

There's a fork for this:
https://github.com/jvilk/locate-java-home/pull/10#issuecomment-906193537

https://github.com/viperproject/locate-java-home

Maybe metals can switch to that?

```
❯ npx locate-java-home                                                                                                                                           
npx: installed 4 in 1.996s
JAVA_HOME directories found: 

❯ echo $JAVA_HOME
env-/nix/store/7gxklxmf8d2c15jmw3i9l67kd2zci3w5-adoptopenjdk-hotspot-bin-11.0.10

✗ npx viperproject/locate-java-home 
npx: installed 5 in 26.395s
JAVA_HOME directories found: 
11.0.10 /nix/store/7gxklxmf8d2c15jmw3i9l67kd2zci3w5-adoptopenjdk-hotspot-bin-11.0.10 [64-bit] [JDK]
11.0.10 /nix/store/7gxklxmf8d2c15jmw3i9l67kd2zci3w5-adoptopenjdk-hotspot-bin-11.0.10/Contents/Home [64-bit] [JDK]
```

Currently, I have to go in to vscode settings over and over to set something dependent on my nix config.

**Installation:**

- Operating system: macOS

**Comment by dos65** [comment]
Additional thing, I have several jdk installed on Ubuntu.
The selected one is jdk 11(using update-alternatives) but extension ignores this facts and always picks jdk17.

**Comment by ArquintL** [comment]
> @ArquintL Would it be possible to publish this on npm? See above ^
It is now available on NPM: [@viperproject/locate-java-home](https://www.npmjs.com/package/@viperproject/locate-java-home)
