### ISSUE TITLE
Confusing error message: Failed to download Metals

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals-vscode#67]
**Describe the bug**

The following error message is confusing: "Failed to download Metals, make sure you have an internet connection, the Metals version '0.4.0' is correct and the Java Home '/usr/lib/jvm/java-1.8.0-openjdk/bin/java' is valid. You can configure the Metals version and Java Home under settings."

Suggestions for improving the message

- test if env variable `FLATPAK_SANDBOX_DIR` is defined, if so may be to blame https://flatpak.org/
- don't warn againt the version '0.4.0' if it's the default version, we know it's correct then

**Comment by olafurpg** [comment]
@jordandlaman is there any relevant information in the `.metals/metals.log` file? What happens if you run the following?
```
$ java -jar ~/.vscode/extensions/scalameta.metals-1.2.0/coursier --help
Coursier 1.1.0-M9
```

**Comment by jordandlaman** [comment]
@olafurpg ```Error: class coursier.cli.Coursier not found```

**Comment by olafurpg** [comment]
@jordandlaman Can you try replacing the `coursier` binary with the latest one?

```
curl -L -o coursier https://git.io/coursier
mv coursier ~/.vscode/extensions/scalameta.metals-1.2.0/coursier
```

The cause of this issue should be fixed https://github.com/coursier/coursier/issues/988
