### ISSUE TITLE
Does not start in a `Remote - SSH` project

### ISSUE THREAD

**Issue by nicolasstucki** [scalameta/metals-vscode#673]
**Describe the bug**

When connecting to a project in remote machine using [Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) the "Import build" does not appear. It also seems to not be possible to start it manually.

**To Reproduce** Steps to reproduce the behavior:

1. Install [Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh)
2. Click on _Remote - SSH_ icon
3. Click on `+` and add an SSH remote
4. Click on `folder +` icon to add a remote project (chose the project directory)
5. Metals does not show the "Import build" popup.

**Expected behavior**

Should be able to import the project. Metals should run on the remote machine.

**Installation:**

- Operating system: macOS 11.4
- VSCode version: 1.52.1
- Remote-SSH VSCode extension version: 0.64.0
- Metals VSCode extension version: 1.10.9
- Metals version: 0.10.6

**Comment by tgodzik** [comment]
Thanks for reporting! Is there anything in the logs? Are you able to run the 'metals: build import' command from the command palette or metals view?

**Comment by nicolasstucki** [comment]
`metals: import build` failed with

<img width="443" alt="Screenshot 2021-09-16 at 09 17 01" src="https://user-images.githubusercontent.com/3648029/133567569-f2b25091-b3b7-43ee-adfa-eb4ccb9cf8dc.png">

I also confirmed that the extension is enabled on the remote machine. In the extension menu, if I select Metals it says: _Extension is enabled on 'SSH: myRemoteUrl'_.

**Comment by nicolasstucki** [comment]
The Metals view gives me this  and nothing happens if I click on `New Scala project`

<img width="213" alt="Screenshot 2021-09-16 at 09 22 16" src="https://user-images.githubusercontent.com/3648029/133568223-0d3379d7-235c-4c47-89c5-2de1be2f8e8b.png">

**Comment by tgodzik** [comment]
This looks like the extension hasn't even initialized. Can you see anything in `Output(Metals)`, in some cases it might be using the local machine settings and that might be interfering with remote ones, although there should we a warning in that case :thinking: 

If there is nothing in Metals output you can take a look at the Extension Host, it should show a reason why an extension was not laoded.

**Comment by nicolasstucki** [comment]
Ok, I found the issue in the metals log 
```
Metals will not start since Dotty is enabled for this workspace. To enable Metals, remove the file /Users/nicolasstucki/GitHub/dotty/.dotty-ide-artifact and run 'Reload window'
```

I removed it and metals started to work.
