### ISSUE TITLE
Metals does not autocomplete scaladocs on scala3

### ISSUE THREAD

**Issue by collinarnett** [scalameta/metals-vscode#696]
**Describe the bug**

Metals does not prompt for scaladoc autocompletion under scala3 based projects.

**To Reproduce** Steps to reproduce the behavior:

1. Create new project using the scala3 template
2. Go to `Main.scala`
3. Type `/**` 
4. No completion available for doc string

**Expected behavior**

Completion of docstring with parameters.

**Screenshots**

![image](https://user-images.githubusercontent.com/38230482/133943803-b79d6e3a-5808-4481-a2fe-ceb901600733.png)

**Installation:**

- Operating system: Linux
- VSCode version: 1.60.1
- VSCode extension version: v1.10.11
- Metals version: 0.10.7

**Additional context**

I noticed this problem when trying to add docstrings to my scala3 project.

**Search terms**

scala3, scala 3, scaladoc, scaladocs

**Comment by tgodzik** [comment]
Thanks for reporting! This is not yet implemented, you can track progress about it in https://github.com/scalameta/metals-feature-requests/issues/181
