### ISSUE TITLE
Metals fails to download in VSCode behind a HTTP proxy

### ISSUE THREAD

**Issue by swiesner-dlr** [scalameta/metals-vscode#70]
**Describe the bug**
I get a connection refused error in VSCode when the metals extension (v 1.2.0) activates the first time.

I'm behind a corporate HTTP proxy, but it's properly configured in the `http.proxy` setting of VSCode.  I also tried to set the `http.proxySupport` to `on`, but no avail.

**To Reproduce**
1. Get behind a HTTP proxy.
2. Install the metals extension and reload the window.
3. Open a folder with a build.sbt.

**Expected behavior**
metals installs properly.

**Screenshots**
![vscode metals](https://user-images.githubusercontent.com/41331064/52114675-f39b1200-260c-11e9-9c0e-4e6e2b915ec5.png)

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.4.0

**Search terms**
HTTP Proxy

**Comment by olafurpg** [comment]
@swiesner-dlr I agree this can be improved, I like your suggestions 👍

**Comment by swiesner-dlr** [comment]
@gabro I just read the [VSCode documentation](https://code.visualstudio.com/docs/setup/network#_legacy-proxy-server-support) again and it looks like `http.proxy` is considered “legacy”, though it's not exactly clear what the replacement is supposed to be.  

Perhaps `JAVA_OPTS` is the better way forward?

@olafurpg Thanks.  Would you like a pull request? If so, which option would you like to see implemented?

**Comment by olafurpg** [comment]
In that case I like respecting `JAVA_OPTS`. We should include the options both when launching metals and also when running `coursier fetch`. A good place to fix this would be somewhere around here 
https://github.com/scalameta/metals-vscode/blob/c2e3196c1e34e9187d1096dc93b30bbd5abc0dd6/src/extension.ts#L84

**Comment by gabro** [comment]
@swiesner-dlr thanks for looking into it. I think it would also be interesting to try setting `http.proxySupport` to `override`. Would you mind trying that? https://code.visualstudio.com/updates/v1_30#_network-proxy-support-for-extensions

**Comment by swiesner-dlr** [comment]
@gabro I saw that option, and I searched VSCode's code for what it does, and from what I saw it only affects HTTP calls from Javascript directly, by injecting proxy settings into the underlying network handler of Electron.  I doesn't look like it automatically propagates to subprocesses or offers a dedicated way to get hold of current proxy settings.

**Comment by olafurpg** [comment]
BTW, note that environment variables don't always propagate when starting VS Code as a GUI applications. It's best to start it with the `code` binary from the terminal to expose `JAVA_OPTS`.

**Comment by swiesner-dlr** [comment]
Thanks for the reminder!  I know that GUI and env variables are a mess on macOS, but this issue affects me only on Linux (I don't have a mac at work), so I'm fine :blush:
