### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by violog** [scalameta/metals-vscode#759]
- Issue Type: `Performance`
- Extension Name: `metals`
- Extension Version: `1.10.15`
- OS Version: `Linux x64 5.15.2-arch1-1`
- VS Code version: `1.62.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/scalameta.metals-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by violog** [comment]
[scalameta.metals-unresponsive.cpuprofile.txt](https://github.com/scalameta/metals-vscode/files/7552612/scalameta.metals-unresponsive.cpuprofile.txt)

**Comment by dos65** [comment]
Thanks for reporting!

Could you add some details to that? Does it happen constantly or after some actions? Which build tools/ scala versions do you use? Are there any errors in Output tab for Metals or in `.metals/metals.log`?

**Comment by tgodzik** [comment]
Let's reopen this if there is more information available.
