### ISSUE TITLE
Metals fails to launch, when not in a workspace

### ISSUE THREAD

**Issue by rreckel** [scalameta/metals-vscode#79]
When opening a file, without opening a workspace/folder beforehand, Metals doesn't launch, but instead reports the following error:

> Unable to find Java 8 home. To fix this problem, update the 'Java Home' setting to point to a Java 8 home directory
> TypeError: Path must be a string. Received undefined

The problem is that during the configuration of the launch, 
the `workspace.rootPath` is used twice:

1. https://github.com/scalameta/metals-vscode/blob/2e68c2c18b8986bcf9b30825d91fa2d6fd7764a5/src/extension.ts#L467

2. https://github.com/scalameta/metals-vscode/blob/2e68c2c18b8986bcf9b30825d91fa2d6fd7764a5/src/getJavaOptions.ts#L7

path.join will fail in this case, because `workspace.rootPath` is `undefined`.

Two possible solutions:
Test if `workspace.rootPath` is undefined and then
1. ignore the rest of the configuration or
2. Return a meaningful error message, telling that metals only works in a workspace/folder.

**Comment by gabro** [comment]
Thanks for reporting, will work on a fix soon!
