### ISSUE TITLE
Publish/support pre-release version of extension

### ISSUE THREAD

**Issue by kpodsiad** [scalameta/metals-vscode#799]
I'm creating this issue to not forget about this feature after Christmas.

VSCode 1.63 (Novemver 2021) supports pre-release version of extensins (see [release notes](https://code.visualstudio.com/updates/v1_63#_pre-release-extensions)) - it may play well with Metals' snapshot releases.

**Comment by Arthurm1** [comment]
This would be handy to help catch things like https://github.com/scalameta/metals/issues/3500 ahead of time.
