### ISSUE TITLE
Register placeholder commands for when Metals didn't start because of Dotty

### ISSUE THREAD

**Issue by gabro** [scalameta/metals-vscode#82]
Metals won't start when a project is identified as a Dotty project, so not to conflict with the Dotty IDE extension.

This causes Metals extension commands not to be registered, leading to confusing errors.

We should register placeholder commands that - when invoked - say something along the lines of

> Metals is not running, because this appears to be a Dotty project

**Comment by olafurpg** [comment]
With https://github.com/scalameta/metals/pull/976, I think it's fine to close this issue in favor of improving the upcoming Dotty support in Metals.
