### ISSUE TITLE
Stuck on `Starting Metals server`

### ISSUE THREAD

**Issue by Pradhyo** [scalameta/metals-vscode#821]
**Describe the bug**

Upgrading to the latest version of the Scala (Metals) `v1.11.1` extension seems to have broken the extension for my project.
It is stuck on `Starting Metals server` for a long time. 
Clicking on either button (New Scala Project/Start Metals) just pops up the same notification again.

![image](https://user-images.githubusercontent.com/7895492/149359786-02cfa000-16c0-4d67-8c69-a49735928877.png)

Notifications:
![image](https://user-images.githubusercontent.com/7895492/149360382-5fe4b2a4-2e68-4cac-be38-275958a465ee.png)

**Expected behavior**
Identifies the project and works fine on v1.10.15.
![image](https://user-images.githubusercontent.com/7895492/149359395-f3cccbac-6429-4bda-a5d5-1e747b0355a6.png)

**Installation:**

- Operating system: macOS
- VSCode version: 1.63.2
- VSCode extension version: v1.11.1
- Metals version: 0.11.0

**Comment by tgodzik** [comment]
Thanks for reporting! Could you check the Metals Output or the Extension host log? It's in the Output view, you can switch between different logs.

Does it start working for you if reload the window? Or maybe reinstall the extension?

**Comment by Pradhyo** [comment]
I tried reloading the window and reinstalling the extension too but it was the same behavior.
I will paste the logs later today, thanks for getting back!

**Comment by KleineDennis** [comment]
You need to set explicit metals.javaHome to your JAVA_HOME path. This is since v1.11.0.

**Comment by tgodzik** [comment]
> Output: Java home: /usr Metals version: 0.11.0
> 
> You need to set explicit **metals.javaHome** to your JAVA_HOME path. This is since v1.11.0. Then everything is working.

That shouldn't be neccessary, does it only impact MacOS users?

**Comment by kpodsiad** [comment]
@Pradhyo @KleineDennis 
Do you have the `JAVA_HOME` variable set? 
What is the result of executing `which java`?

**Comment by KleineDennis** [comment]
> 

~/workspace % where java
/usr/bin/java

**Comment by KleineDennis** [comment]
@kpodsiad  it seems to be, since version 0.11.0 you **need** to set the JAVA_HOME variable.

**Comment by Pradhyo** [comment]
Everything for the same for me.

Output:
Java home: /usr
Metals version: 0.11.0

where java
/usr/bin/java

JAVA_HOME wasn't set.

Adding this to my ~/.zshrc fixed it                                                                                                                                                                  
`export JAVA_HOME=$(/usr/libexec/java_home)`

Thanks a lot guys, please feel free to close or let me know if I can close this.

**Comment by kpodsiad** [comment]
There's an issue when java is located at the `/usr/bin/java` and `/usr/bin/java` is not a symlink.

A little bit of explanation without digging into details: metals vscode extension locates that java is available at `/usr/bin/java` and assumes that `realPath(/usr/bin/java)/../..` (where `realPath` follows a symlink) should a java home (hence `Java home: /usr` in output); then a java process is spawned using `/usr/bin/java`. However, it's still unclear to us why the process is hanging since `/usr/bin/java` points to a valid java executable :/

**Comment by Pradhyo** [comment]
got it - thanks for the details.
Looks like it's fixed but please let me know if you need anything else from me.

**Comment by zalbia** [comment]
In my case it was bloop.json in ~/.bloop/bloop.json with the following offending content:
```JSON
{"javaHome":"/usr/bin/java"}
```
