### ISSUE TITLE
Code completion should be case insensitive

### ISSUE THREAD

**Issue by doofin** [scalameta/metals-vscode#842]
Currently,Code completion is case sensitive

**Comment by tgodzik** [comment]
Thanks for reporting! The completions behave in this way on purpose. You can use the capital letter only to match longer class names such for example:
`SPC` string will match `ScalaPresentationCompiler`.

**Comment by doofin** [comment]
Is there an option to change this? It can be customized in intellj

**Comment by tgodzik** [comment]
There is no option for that currently, you can for sure open up a feature request in https://github.com/scalameta/metals-feature-requests/issues, where it can be voted on.

**Comment by doofin** [comment]
Thanks!
