### ISSUE TITLE
Update Market Place description

### ISSUE THREAD

**Issue by ShalokShalom** [scalameta/metals-vscode#935]
The current marketplace readme reveals nothing about the currently supported version. 
It is not possible, to see if Scala 3 is supported, or anything like that. 
Also, its not visible when it was uploaded for the first or last time. 

![Screenshot_207](https://user-images.githubusercontent.com/6344099/161742202-43ecb4f3-7f3b-4c39-b501-0867e6ee9ee6.png)

**Comment by kpodsiad** [comment]
Thanks for reporting @ShalokShalomm! I'll take a look at this.

**Comment by kpodsiad** [comment]
I checked locally and also on the [website](https://marketplace.visualstudio.com/items?itemName=scalameta.metals) and it seems like the date is being resolved correctly. I don't know where the date is coming from, but we do not set this manually.

@ShalokShalom do you use vscode or vscodium?

**Comment by ShalokShalom** [comment]
VSCode. Guess this is a vscode issue then.

**Comment by kpodsiad** [comment]
What's also strange are the numbers of downloads and ratings, it's stale and far low than the data available on the marketplace [webiste](https://marketplace.visualstudio.com/items?itemName=scalameta.metals).

**Comment by ShalokShalom** [comment]
I have seen the issue I reported on multiple other project sites as well. 
You might like to report that, I guess its more sensible if a project itself does so, since you have access to the marketplace account and all its data.
