### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by khanr1** [scalameta/metals-vscode#967]
- Issue Type: `Bug`
- Extension Name: `metals`
- Extension Version: `1.16.0`
- OS Version: `Linux x64 5.13.0-40-generic`
- VS Code version: `1.66.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 8449,
		"activateCallTime": 4,
		"activateResolvedTime": 19484,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "scalameta.metals",
				"_lower": "scalameta.metals"
			},
			"activationEvent": "onLanguage:scala"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by tgodzik** [comment]
Thanks for reporting! Unfortunately it's no possible to see exactly what is going on based on the json content. Could you explain a bit more about the problem?
