### ISSUE TITLE
Commands missing from command palatte

### ISSUE THREAD

**Issue by japgolly** [scalameta/metals-vscode#97]
**Describe the bug**

When opening the command palette, it used to be the case that you could type `metals` and see a bunch of Metals commands; in the README there is a screenshot of a user searching `>import` and `Metals: import build` appearing. As of version 1.3.1, these commands no longer appear. Typing `metals` or `import` results in an empty list.

**To Reproduce** Steps to reproduce the behaviour:

1. ctrl-shift-P
1. type `metal`
1. see no results

**Expected behavior**

Items such as `Metals: import build` should be present

**Installation:**

- Operating system: Linux
- VSCode version: 1.33.1
- VSCode extension version: 1.3.1
- Metals version: 0.5.0

**Comment by japgolly** [comment]
Hmmm, it's begun appearing now. The issue might've been that one of my sources didn't compile, or that may've just been a coincidence.

**Comment by gabro** [comment]
Hi @japgolly, thanks for reporting.
Commands only appear when on a Scala or sbt file.
This is to prevent Metals command to show up when you're not on a scala project.

Unfortunately there is no API to make them appear based on the content of the workspace (e.g. whether you have a build.sbt), this is a known limitation of vscode.

**Comment by gabro** [comment]
For context, this was introduced back in https://github.com/scalameta/metals-vscode/pull/31 to prevent spurious errors
